// Canonical registry of brewers (drippers). Authored content lives in
// [docs/taxonomies/brewers.md](../docs/taxonomies/brewers.md); this file is
// the validation mirror generated from Chris's authored CSV (Registry -
// Taxonomy - Drippers and filter papers - Drippers.csv, 47 rows / 45
// distinct, plus xBloom net-new = 46 canonical brewers).
//
// Sprint 1f (2026-04-26): structural port + adoption. brews.brewer is a
// text-only column (no FK to a brewers table). Adding a new brewer is a
// deliberate edit — add a `BrewerEntry` to `BREWERS` and update brewers.md.
//
// Material axis (Glass / Porcelain / Ceramic) is intentionally NOT carried
// in the canonical name. Material drift in legacy DB strings ("Hario V60
// (glass)" / "UFO Ceramic" / "April Glass") strips to canonical via the
// alias map. Per-brewer material isn't tracked anywhere in this taxonomy
// — Chris's authored CSV doesn't surface it.
//
// Orea v1-3 vs v4 ambiguity: 14 legacy "Orea Glass" / "Orea Porcelain"
// brews default to "Orea v4" via alias (Chris's plan-mode answer; v4 is
// newer and the most likely current driver). Refine via /brews/[id]/edit
// per-brew if the exact version matters.
//
// xBloom is a net-new entry (missing from the authored CSV but Chris owns
// it and 1 legacy brew used it). Mirror of how Espro Bloom was added on
// the filter side post-CSV-author.

import { makeCanonicalLookup, type CanonicalLookup } from './canonical-registry'

// ---------------------------------------------------------------------------
// Type shape
// ---------------------------------------------------------------------------

export type BrewerCategory =
  | 'Cone filter drippers'
  | 'Wave Filter Drippers'
  | 'Trapezoid filter drippers'
  | 'Round/circle filter drippers'
  | 'Self-filtering drippers'

export interface BrewerEntry {
  name: string
  displayName?: string
  manufacturer: string
  category: BrewerCategory | string
  paperType: string
  doseSize: string
  bedGeometry: string
  bypassProfile: string
  flowControl: string
  restrictionSource: string
  agitationTolerance: string
  brewArchetype: string
  accessories?: string
  owned?: boolean
  location?: string
  primaryUseCase?: string
}

export const BREWERS: readonly BrewerEntry[] = [
  {
    name: "Aeropress",
    manufacturer: "AeroPress",
    category: "Round/circle filter drippers",
    paperType: "Disc (64mm)",
    doseSize: "10g to 30g",
    bedGeometry: "Cylindrical / immersion",
    bypassProfile: "Low",
    flowControl: "Pressure / immersion",
    restrictionSource: "Filter + pressure",
    agitationTolerance: "High",
    brewArchetype: "Pressure / vacuum system",
    accessories: "Prismo / Puckpuck",
  },
  {
    name: "April",
    manufacturer: "April",
    category: "Wave Filter Drippers",
    paperType: "Flat (Kalita 155) + trapezoid option",
    doseSize: "15g to 25g",
    bedGeometry: "Flat / shallow",
    bypassProfile: "Low",
    flowControl: "Immersion hybrid",
    restrictionSource: "Valve-controlled",
    agitationTolerance: "High",
    brewArchetype: "Immersion hybrid",
    accessories: "Immersion base / stopper",
    owned: true,
    location: "Home, Office",
    primaryUseCase: "Structured clarity (restricted flat control)",
  },
  {
    name: "Brewista Tornado",
    manufacturer: "Brewista",
    category: "Cone filter drippers",
    paperType: "Conical (Cafec Abaca+ or folded V60)",
    doseSize: "10g to 25g",
    bedGeometry: "Conical / medium",
    bypassProfile: "Medium",
    flowControl: "Passive percolation",
    restrictionSource: "Geometry-limited",
    agitationTolerance: "Medium",
    brewArchetype: "Clarity cone",
    accessories: "Drip tray base",
  },
  {
    name: "Cafec Deep27",
    manufacturer: "Cafec",
    category: "Cone filter drippers",
    paperType: "Conical (Cafec Abaca+ / V60)",
    doseSize: "10g to 15g",
    bedGeometry: "Conical / very deep",
    bypassProfile: "Medium",
    flowControl: "Passive percolation",
    restrictionSource: "Geometry-limited",
    agitationTolerance: "Medium",
    brewArchetype: "Clarity cone",
    accessories: "None",
  },
  {
    name: "Cafec Deep45",
    manufacturer: "Cafec",
    category: "Cone filter drippers",
    paperType: "Conical (Cafec Abaca+)",
    doseSize: "15g to 25g",
    bedGeometry: "Conical / deep",
    bypassProfile: "Medium",
    flowControl: "Passive percolation",
    restrictionSource: "Geometry-limited",
    agitationTolerance: "Medium",
    brewArchetype: "Clarity cone",
    accessories: "None",
  },
  {
    name: "Cafec Deep45 Arita Pro",
    manufacturer: "Cafec",
    category: "Cone filter drippers",
    paperType: "Conical (Cafec Abaca+)",
    doseSize: "15g to 25g+",
    bedGeometry: "Conical / deep",
    bypassProfile: "Medium",
    flowControl: "Passive percolation",
    restrictionSource: "Geometry-limited",
    agitationTolerance: "Medium",
    brewArchetype: "Clarity cone",
    accessories: "None",
  },
  {
    name: "Cafec Flower",
    manufacturer: "Cafec",
    category: "Cone filter drippers",
    paperType: "Conical (V60 01-02)",
    doseSize: "10g to 25g",
    bedGeometry: "Conical / medium",
    bypassProfile: "Medium",
    flowControl: "Passive percolation",
    restrictionSource: "Geometry-limited",
    agitationTolerance: "Medium",
    brewArchetype: "Clarity cone",
    accessories: "None",
  },
  {
    name: "Cafec Oval",
    manufacturer: "Cafec",
    category: "Trapezoid filter drippers",
    paperType: "Trapezoid",
    doseSize: "10g to 25g+",
    bedGeometry: "Trapezoid / medium",
    bypassProfile: "Medium",
    flowControl: "Passive percolation",
    restrictionSource: "Geometry-limited",
    agitationTolerance: "Medium",
    brewArchetype: "Stability flat",
    accessories: "None",
  },
  {
    name: "Chemex",
    manufacturer: "Chemex",
    category: "Cone filter drippers",
    paperType: "Square paper folded cone",
    doseSize: "15g to 25g+",
    bedGeometry: "Conical / deep",
    bypassProfile: "Low",
    flowControl: "Passive percolation",
    restrictionSource: "Paper-limited",
    agitationTolerance: "Low",
    brewArchetype: "Clarity cone",
    accessories: "None",
  },
  {
    name: "Chemex Funnex",
    manufacturer: "Chemex",
    category: "Cone filter drippers",
    paperType: "Proprietary cone filter",
    doseSize: "5g to 15g",
    bedGeometry: "Conical / deep",
    bypassProfile: "Low",
    flowControl: "Passive percolation",
    restrictionSource: "Paper-limited",
    agitationTolerance: "Low",
    brewArchetype: "Clarity cone",
    accessories: "None",
    owned: true,
    location: "Home",
    primaryUseCase: "I primarily use for small odd dose size (less than 15g)",
  },
  {
    name: "Clever",
    manufacturer: "Clever",
    category: "Trapezoid filter drippers",
    paperType: "Trapezoid / folded cone",
    doseSize: "15g to 25g+",
    bedGeometry: "Conical / deep",
    bypassProfile: "Low",
    flowControl: "Valve (immersion)",
    restrictionSource: "Valve-controlled",
    agitationTolerance: "High",
    brewArchetype: "Immersion hybrid",
    accessories: "None",
  },
  {
    name: "Espro",
    manufacturer: "Espro",
    category: "Wave Filter Drippers",
    paperType: "Proprietary tall wave",
    doseSize: "15g to 25g",
    bedGeometry: "Flat / medium",
    bypassProfile: "Low",
    flowControl: "Passive percolation",
    restrictionSource: "Paper-limited",
    agitationTolerance: "Medium",
    brewArchetype: "Stability flat",
    accessories: "None",
  },
  {
    name: "Fellow Duo",
    manufacturer: "Fellow",
    category: "Self-filtering drippers",
    paperType: "None (metal mesh)",
    doseSize: "15g to 25g+",
    bedGeometry: "Flat / medium",
    bypassProfile: "None",
    flowControl: "Valve (immersion)",
    restrictionSource: "Metal mesh",
    agitationTolerance: "High",
    brewArchetype: "Immersion hybrid",
    accessories: "None",
  },
  {
    name: "Fellow Stagg X/XF",
    manufacturer: "Fellow",
    category: "Wave Filter Drippers",
    paperType: "Flat (Kalita 155/185)",
    doseSize: "15g to 25g+",
    bedGeometry: "Flat / medium",
    bypassProfile: "Low",
    flowControl: "Passive percolation",
    restrictionSource: "Geometry-limited",
    agitationTolerance: "Medium",
    brewArchetype: "Stability flat",
    accessories: "Funnel",
  },
  {
    name: "Phin",
    manufacturer: "Generic",
    category: "Self-filtering drippers",
    paperType: "None or optional round paper",
    doseSize: "10g to 15g",
    bedGeometry: "Cylindrical / deep",
    bypassProfile: "None",
    flowControl: "Gravity / immersion",
    restrictionSource: "Metal screen",
    agitationTolerance: "Low",
    brewArchetype: "Immersion hybrid",
    accessories: "None",
  },
  {
    name: "Hario Switch",
    manufacturer: "Hario",
    category: "Cone filter drippers",
    paperType: "Conical (V60 01-03)",
    doseSize: "10g to 25g+",
    bedGeometry: "Conical / deep",
    bypassProfile: "Medium",
    flowControl: "Valve (immersion hybrid)",
    restrictionSource: "Valve-controlled",
    agitationTolerance: "High",
    brewArchetype: "Immersion hybrid",
    accessories: "Switch base / Goodswitch lever",
    owned: true,
    location: "Home",
    primaryUseCase: "Full immersion control (valve-driven extraction)",
  },
  {
    name: "Hario V60",
    manufacturer: "Hario",
    category: "Cone filter drippers",
    paperType: "Conical (all sizes)",
    doseSize: "10g to 25g+",
    bedGeometry: "Conical / deep",
    bypassProfile: "Medium",
    flowControl: "Passive percolation",
    restrictionSource: "Geometry-limited",
    agitationTolerance: "High",
    brewArchetype: "Clarity cone",
    accessories: "Hario drip assist",
    owned: true,
    location: "Home",
    primaryUseCase: "Peak clarity (high-bypass separation)",
  },
  {
    name: "Hario Alpha",
    manufacturer: "Hario",
    category: "Cone filter drippers",
    paperType: "Conical (V60 02)",
    doseSize: "10g to 25g",
    bedGeometry: "Conical / medium",
    bypassProfile: "Medium",
    flowControl: "Passive percolation",
    restrictionSource: "Geometry-limited",
    agitationTolerance: "Medium",
    brewArchetype: "Clarity cone",
    accessories: "None",
  },
  {
    name: "Hario Flow",
    manufacturer: "Hario",
    category: "Cone filter drippers",
    paperType: "Wave (Kalita 155)",
    doseSize: "15g to 25g",
    bedGeometry: "Flat / shallow",
    bypassProfile: "Low",
    flowControl: "Passive percolation",
    restrictionSource: "Geometry-limited",
    agitationTolerance: "Medium",
    brewArchetype: "Stability flat",
    accessories: "None",
  },
  {
    name: "Hario Mugen",
    manufacturer: "Hario",
    category: "Cone filter drippers",
    paperType: "Conical (V60 02)",
    doseSize: "15g to 25g",
    bedGeometry: "Conical / deep",
    bypassProfile: "Low",
    flowControl: "Passive percolation",
    restrictionSource: "Geometry-limited",
    agitationTolerance: "Low",
    brewArchetype: "Clarity cone (low bypass variant)",
    accessories: "None",
  },
  {
    name: "Hario Suiren",
    manufacturer: "Hario",
    category: "Cone filter drippers",
    paperType: "Conical (V60 02)",
    doseSize: "15g to 25g",
    bedGeometry: "Conical / open",
    bypassProfile: "High",
    flowControl: "Passive percolation",
    restrictionSource: "Geometry-limited",
    agitationTolerance: "High",
    brewArchetype: "Clarity cone",
    accessories: "Custom rib attachments",
  },
  {
    name: "Hario Switch RAN",
    manufacturer: "Hario",
    category: "Cone filter drippers",
    paperType: "Conical (V60 02)",
    doseSize: "15g to 25g",
    bedGeometry: "Conical / deep",
    bypassProfile: "Medium",
    flowControl: "Valve (immersion hybrid)",
    restrictionSource: "Valve-controlled",
    agitationTolerance: "High",
    brewArchetype: "Immersion hybrid",
    accessories: "Switch base",
  },
  {
    name: "Hario V60 NEO",
    manufacturer: "Hario",
    category: "Cone filter drippers",
    paperType: "Conical (01-02)",
    doseSize: "10g to 25g",
    bedGeometry: "Conical / medium",
    bypassProfile: "Medium",
    flowControl: "Passive percolation",
    restrictionSource: "Geometry-limited",
    agitationTolerance: "Medium",
    brewArchetype: "Clarity cone",
    accessories: "Switch base compatibility",
  },
  {
    name: "Hario W60",
    manufacturer: "Hario",
    category: "Cone filter drippers",
    paperType: "Conical + mesh hybrid (V60 02)",
    doseSize: "15g to 25g",
    bedGeometry: "Hybrid / suspended bed",
    bypassProfile: "High",
    flowControl: "Hybrid (mesh + paper)",
    restrictionSource: "Mesh + paper",
    agitationTolerance: "High",
    brewArchetype: "Clarity cone (hybrid high bypass)",
    accessories: "None",
  },
  {
    name: "Kalita Tsubame",
    manufacturer: "Kalita",
    category: "Wave Filter Drippers",
    paperType: "Wave (155)",
    doseSize: "10g to 25g",
    bedGeometry: "Flat / medium",
    bypassProfile: "Low",
    flowControl: "Passive percolation",
    restrictionSource: "Geometry-limited",
    agitationTolerance: "Medium",
    brewArchetype: "Stability flat",
    accessories: "None",
    owned: true,
    location: "Home, Office",
    primaryUseCase: "Neutral flat baseline (geometry reference)",
  },
  {
    name: "Kalita Mino",
    manufacturer: "Kalita",
    category: "Wave Filter Drippers",
    paperType: "Wave (185)",
    doseSize: "15g to 25g",
    bedGeometry: "Flat / medium",
    bypassProfile: "Low",
    flowControl: "Passive percolation",
    restrictionSource: "Geometry-limited",
    agitationTolerance: "Medium",
    brewArchetype: "Stability flat",
    accessories: "None",
  },
  {
    name: "Kalita Wave",
    manufacturer: "Kalita",
    category: "Wave Filter Drippers",
    paperType: "Wave (155-185)",
    doseSize: "10g to 25g",
    bedGeometry: "Flat / medium",
    bypassProfile: "Low",
    flowControl: "Passive percolation",
    restrictionSource: "Geometry-limited",
    agitationTolerance: "Medium",
    brewArchetype: "Stability flat",
    accessories: "None",
  },
  {
    name: "Melitta",
    manufacturer: "Melitta",
    category: "Trapezoid filter drippers",
    paperType: "Trapezoid",
    doseSize: "10g to 25g+",
    bedGeometry: "Trapezoid / medium",
    bypassProfile: "Low",
    flowControl: "Passive percolation",
    restrictionSource: "Geometry-limited",
    agitationTolerance: "Low",
    brewArchetype: "Stability flat",
    accessories: "None",
  },
  {
    name: "Melodrip Colum",
    manufacturer: "Melodrip",
    category: "Cone filter drippers",
    paperType: "Conical (custom trimmed papers)",
    doseSize: "10g to 25g",
    bedGeometry: "Conical / shallow",
    bypassProfile: "Low",
    flowControl: "Two-stage percolation",
    restrictionSource: "Device-controlled",
    agitationTolerance: "Low",
    brewArchetype: "Stability flat (two-stage assist)",
    accessories: "None",
  },
  {
    name: "Next Level LVL-10",
    manufacturer: "NextLevel",
    category: "Round/circle filter drippers",
    paperType: "Round filter",
    doseSize: "25g+",
    bedGeometry: "Flat / deep",
    bypassProfile: "None (zero bypass)",
    flowControl: "Zero-bypass percolation",
    restrictionSource: "Paper-limited",
    agitationTolerance: "Low",
    brewArchetype: "Zero-bypass push",
    accessories: "Drip assist lid",
  },
  {
    name: "Next Level Pulsar",
    manufacturer: "NextLevel",
    category: "Round/circle filter drippers",
    paperType: "Round filter",
    doseSize: "15g to 25g+",
    bedGeometry: "Flat / deep",
    bypassProfile: "None (zero bypass)",
    flowControl: "Valve (immersion + percolation)",
    restrictionSource: "Valve-controlled",
    agitationTolerance: "High",
    brewArchetype: "Zero-bypass push (hybrid valve)",
    accessories: "Filter discs / drip assist lid",
  },
  {
    name: "Normcore 2-in-1",
    manufacturer: "Normcore",
    category: "Cone filter drippers",
    paperType: "Conical (V60 01) + Wave (155)",
    doseSize: "10g to 25g",
    bedGeometry: "Hybrid / variable",
    bypassProfile: "Variable (low–medium)",
    flowControl: "Passive percolation",
    restrictionSource: "Geometry-limited",
    agitationTolerance: "Medium",
    brewArchetype: "Hybrid (variable archetype)",
    accessories: "None",
  },
  {
    name: "Orea v1-3",
    manufacturer: "Orea",
    category: "Wave Filter Drippers",
    paperType: "Flat (Kalita 155-185)",
    doseSize: "10g to 25g",
    bedGeometry: "Flat / shallow",
    bypassProfile: "Low",
    flowControl: "Passive percolation",
    restrictionSource: "Geometry-limited",
    agitationTolerance: "Medium",
    brewArchetype: "Stability flat",
    accessories: "Negotiator",
    owned: true,
    location: "Home",
    primaryUseCase: "Clarity-balanced flat (low-bypass stability)",
  },
  {
    name: "Orea v4",
    manufacturer: "Orea",
    category: "Cone filter drippers",
    paperType: "Flat (Kalita 155-185) + Apex cone option",
    doseSize: "10g to 25g",
    bedGeometry: "Flat / shallow",
    bypassProfile: "Low",
    flowControl: "Modular (base-dependent)",
    restrictionSource: "Base-controlled",
    agitationTolerance: "Medium",
    brewArchetype: "Stability flat (modular)",
    accessories: "Negotiator / interchangeable bases",
  },
  {
    name: "Orea Big Boy",
    manufacturer: "Orea",
    category: "Wave Filter Drippers",
    paperType: "Flat (custom large)",
    doseSize: "25g+",
    bedGeometry: "Flat / shallow",
    bypassProfile: "Low",
    flowControl: "Passive percolation",
    restrictionSource: "Geometry-limited",
    agitationTolerance: "Medium",
    brewArchetype: "Stability flat",
    accessories: "Negotiator",
  },
  {
    name: "Orea Z1",
    manufacturer: "Orea",
    category: "Round/circle filter drippers",
    paperType: "Round (70mm Sibarist)",
    doseSize: "10g to 25g",
    bedGeometry: "Flat / shallow",
    bypassProfile: "None (zero bypass)",
    flowControl: "Immersion hybrid",
    restrictionSource: "Valve-controlled",
    agitationTolerance: "High",
    brewArchetype: "Zero-bypass push",
    accessories: "Immersion base / travel case",
  },
  {
    name: "Origami",
    manufacturer: "Origami",
    category: "Wave Filter Drippers",
    paperType: "Wave (Kalita 155-185)",
    doseSize: "10g to 25g",
    bedGeometry: "Flat / shallow",
    bypassProfile: "Low",
    flowControl: "Passive percolation",
    restrictionSource: "Geometry-limited",
    agitationTolerance: "Medium",
    brewArchetype: "Stability flat",
    accessories: "Base",
  },
  {
    name: "Origami Pinn",
    manufacturer: "Origami",
    category: "Cone filter drippers",
    paperType: "Conical (V60 / 55°)",
    doseSize: "10g to 25g",
    bedGeometry: "Conical / shallow",
    bypassProfile: "High",
    flowControl: "Passive percolation",
    restrictionSource: "Geometry-limited",
    agitationTolerance: "High",
    brewArchetype: "Clarity cone",
    accessories: "Folding template",
  },
  {
    name: "OXO",
    manufacturer: "OXO",
    category: "Trapezoid filter drippers",
    paperType: "Trapezoid (Cafec 102)",
    doseSize: "15g to 25g",
    bedGeometry: "Trapezoid / medium",
    bypassProfile: "Low",
    flowControl: "Passive percolation",
    restrictionSource: "Geometry-limited",
    agitationTolerance: "Low",
    brewArchetype: "Stability flat",
    accessories: "None",
  },
  {
    name: "Oxo Rapid Brewer (ORB)",
    manufacturer: "OXO",
    category: "Round/circle filter drippers",
    paperType: "Round (Aeropress-like)",
    doseSize: "15g to 25g",
    bedGeometry: "Cylindrical / shallow",
    bypassProfile: "Low",
    flowControl: "Pressure / pump",
    restrictionSource: "Pressure",
    agitationTolerance: "High",
    brewArchetype: "Pressure / vacuum system",
    accessories: "None",
    owned: true,
    location: "Home",
    primaryUseCase: "I primarily use for traveling for making \"soup\", especially good with very expressive/funky coffees",
  },
  {
    name: "Palatti Terra",
    manufacturer: "Palatti",
    category: "Trapezoid filter drippers",
    paperType: "Trapezoid (Cafec 102)",
    doseSize: "15g to 25g",
    bedGeometry: "Trapezoid / medium",
    bypassProfile: "Medium",
    flowControl: "Passive percolation",
    restrictionSource: "Geometry-limited",
    agitationTolerance: "Medium",
    brewArchetype: "Stability flat",
    accessories: "Drip stand",
  },
  {
    name: "Sibarist Brewing System",
    manufacturer: "Sibarist",
    category: "Cone filter drippers",
    paperType: "System-specific (CONE BS FAST / B3)",
    doseSize: "15g to 25g",
    bedGeometry: "Conical / deep (precision-controlled)",
    bypassProfile: "None (perfect seal)",
    flowControl: "Passive percolation (system-controlled)",
    restrictionSource: "Paper + system-integrated geometry",
    agitationTolerance: "Medium",
    brewArchetype: "Clarity cone (system-level)",
    accessories: "HALO – Minimalist holder for effortless filter handling from grinder to brew to disposal. No rinsing needed, no dripper adaptation required.\nBREWING CHAMBER – Hand-blown borosilicate glass chamber that locks in heat an aromas. Its inner tower design minimizes heat loss and maximizes flavor capture.\nEXCHANGER – Temperature-control insert for the BREWING CHAMBER. Fill with cold or warm water to adjust serving temperature while preserving aroma and flavor richness.",
    owned: true,
    location: "Home",
    primaryUseCase: "System-level precision clarity (eliminate fit variability and isolate extraction variables)",
  },
  {
    name: "Sworks Bottomless",
    manufacturer: "Sworks",
    category: "Wave Filter Drippers",
    paperType: "Wave (Kalita 155)",
    doseSize: "10g to 25g",
    bedGeometry: "Flat / shallow",
    bypassProfile: "Low",
    flowControl: "Valve (immersion hybrid)",
    restrictionSource: "Valve-controlled",
    agitationTolerance: "High",
    brewArchetype: "Immersion hybrid",
    accessories: "Interchangeable bases",
    owned: true,
    location: "Office",
    primaryUseCase: "Hybrid manipulation (open + valve control)",
  },
  {
    name: "UFO",
    manufacturer: "UFO",
    category: "Cone filter drippers",
    paperType: "Conical (custom 80°)",
    doseSize: "10g to 25g",
    bedGeometry: "Conical / open",
    bypassProfile: "High",
    flowControl: "Passive percolation",
    restrictionSource: "Geometry-limited",
    agitationTolerance: "High",
    brewArchetype: "Clarity cone",
    accessories: "Folding template / base",
    owned: true,
    location: "Home",
    primaryUseCase: "Extreme clarity (max bypass cone)",
  },
  {
    name: "Weber Workshops Bird",
    manufacturer: "Weber Workshops",
    category: "Round/circle filter drippers",
    paperType: "Round filter",
    doseSize: "15g to 25g",
    bedGeometry: "Cylindrical / deep",
    bypassProfile: "None (zero bypass)",
    flowControl: "Vacuum / piston",
    restrictionSource: "Vacuum-controlled",
    agitationTolerance: "Low",
    brewArchetype: "Zero-bypass push",
    accessories: "None",
    owned: true,
    location: "Home",
    primaryUseCase: "Max extraction pressure (zero-bypass vacuum)",
  },
  {
    name: "xBloom",
    manufacturer: "xBloom",
    category: "Round/circle filter drippers",
    paperType: "Flat (Kalita 155-185)",
    doseSize: "15g to 25g",
    bedGeometry: "Flat / shallow",
    bypassProfile: "Low",
    flowControl: "Automated percolation",
    restrictionSource: "Device-controlled",
    agitationTolerance: "Low",
    brewArchetype: "Stability flat (automated)",
    accessories: "xBloom Studio (smart base)",
    owned: true,
    location: "Home, Office",
    primaryUseCase: "Automated stability baseline (smart-controlled flat extraction)",
  },
]

export const BREWER_NAMES: readonly string[] = BREWERS.map((b) => b.name)

// canonical-registry factory's `canonicalize()` walks: case-insensitive
// canonical → alias → substring → 3-char prefix. Aliases below are the
// explicit "we know what you mean" layer for material qualifiers, version
// drift, and prefix junk.

export const BREWER_ALIASES: Record<string, string> = {
  "Orea Glass": "Orea v4",
  "OREA Glass": "Orea v4",
  "Orea Glass (open bottom, no negotiator)": "Orea v4",
  "Orea (glass or porcelain)": "Orea v4",
  "Orea (porcelain or glass)": "Orea v4",
  "Orea Porcelain": "Orea v4",
  "Orea porcelain": "Orea v4",
  "April Glass": "April",
  "April glass": "April",
  "April Brewer (glass)": "April",
  "April Glass Brewer": "April",
  "April Brewer": "April",
  "April Brewer Glass": "April",
  "Hario V60 (glass)": "Hario V60",
  "Hario V60 Glass": "Hario V60",
  "Hario V60 glass": "Hario V60",
  "Hario Switch (glass)": "Hario Switch",
  "UFO Ceramic": "UFO",
  "UFO Ceramic Dripper": "UFO",
  "Brewer: UFO Ceramic": "UFO",
  "Kalita Wave Tsubame 155": "Kalita Tsubame",
  "SWORKS Bottomless Dripper": "Sworks Bottomless",
  "Sworks Bottomless Dripper": "Sworks Bottomless",
  "xBloom (flat-bottom percolation)": "xBloom",
}

export const BREWER_LOOKUP: CanonicalLookup = makeCanonicalLookup(
  BREWER_NAMES,
  BREWER_ALIASES,
)

// Back-compat exports.
export const isCanonicalBrewer = BREWER_LOOKUP.isCanonical
export const findClosestBrewer = BREWER_LOOKUP.findClosest

export function getBrewerEntry(name: string | null | undefined): BrewerEntry | null {
  if (!name) return null
  const canonical = BREWER_LOOKUP.canonicalize(name)
  if (!canonical) return null
  return BREWERS.find((b) => b.name === canonical) ?? null
}

export function getBrewerDisplayName(name: string | null | undefined): string {
  if (!name) return ''
  const e = getBrewerEntry(name)
  return e?.displayName ?? e?.name ?? name
}
