// Canonical registry of filter papers. Authored content lives in
// [docs/skills/brewing-equipment-expert/cluster/filters.md](../docs/skills/brewing-equipment-expert/cluster/filters.md);
// this file is the validation mirror generated from Chris's authored CSV
// (Registry - Taxonomy - Drippers and filter papers - Papers.csv, 69 rows
// pre-dedupe).
//
// Sprint 1f (2026-04-26): structural port + adoption. brews.filter is a
// text-only column (no FK to a filters table). Adding a new filter is a
// deliberate edit — add a `FilterEntry` to `FILTERS` and update the
// authored cluster doc.
//
// Wave 1 (2026-05-26, ADR-0011): authored doc migrated from
// docs/taxonomies/filters.md to the Brewing Equipment Expert sub-skill
// cluster. Old path is a redirect stub for back-compat.
//
// Paper sizes (S/M) and fold variants are intentionally NOT carried as
// separate canonical entries. Sibarist FLAT FAST Size S vs Size M are the
// same canonical paper for this taxonomy — strip the size suffix on
// canonicalize.
//
// "Espro Bloom" in legacy DB strings was a misnaming of the xBloom
// Premium Paper Filters (XBLOOM-STD), per Chris's plan-mode confirm.
// All 16 brews labeled "Espro Bloom*" alias to "xBloom Premium Paper
// Filters" — not a net-new canonical.
//
// Sibarist filter drift is brewer-aware. "Sibarist FAST" or "Sibarist
// FAST Cone" can mean FLAT FAST / CONE FAST / UFO FAST depending on the
// brewer paired with the brew. The migration handles ambiguous strings
// per-row with (brewer, filter) WHERE clauses; the runtime alias map
// only covers unambiguous variants (Sibarist UFO Fast Cone always means
// UFO FAST regardless of brewer; Sibarist FAST Flat always means FLAT
// FAST since "flat" is the shape descriptor).

import { makeCanonicalLookup, type CanonicalLookup } from './canonical-registry'

// ---------------------------------------------------------------------------
// Type shape
// ---------------------------------------------------------------------------

export interface FilterEntry {
  name: string
  displayName?: string
  manufacturer: string
  sku: string
  link?: string
  paperShape: string
  sizeStandard: string
  fitsBrewers: string[]
  sealFitType: string
  material: string
  thickness: string
  crepeStructure: string
  flowRate: string
  flowConsistency: string
  bypassInteraction: string
  cloggingRisk: string
  clarity: string
  body: string
  sweetnessExpression: string
  paperTechnology: string
  bestArchetype: string
  compatibleSystems: string
  owned?: boolean
  location?: string
  primaryUseCase?: string
  // Research Project #1 (cone-filter-drawdown, 2026-05-23) extension:
  // measured loaded-bed drawdown from controlled testing. Raw drawdown
  // stored at measurementDose; do not normalize across doses (drawdown-vs-dose
  // isn't linear). bedBehaviorUnderLoad is observation-time qualitative axis
  // parallel to flowRate. See docs/research-projects/{measurementProject}.md
  // for the protocol + raw data.
  measuredDrawdownSec?: number
  measurementDose?: string
  measurementBaseline?: string
  measurementDate?: string
  measurementProject?: string
  bedBehaviorUnderLoad?: 'stable' | 'late-forming-crater' | 'pour-impact-crater' | 'mixed'
  // measurementNote (Project #2, 2026-05-24): free-text context that the
  // structured fields can't capture — size variant tested, accessory used,
  // hand-fold provenance, size-confound flags, design-intent notes. Optional;
  // populate when the measurement number alone would mislead without context.
  measurementNote?: string
}

export const FILTERS: readonly FilterEntry[] = [
  // Project #2 (flat-bottom-filter-drawdown, 2026-05-24): measurement deferred —
  // oversized for Orea v4 (would have required forced compression), AND no peer
  // paper in Orea brewer to compare against (cohort-of-one). Re-measurement
  // candidate when (a) second April-fit paper enters inventory, OR (b) Project #3
  // native-brewer protocol covers it via the April brewer. See:
  // docs/research-projects/flat-bottom-filter-drawdown.md § Notes
  //
  // PaperShape audit note (Project #3 prep 2026-05-24): April paper has flat
  // bottom + fluted walls — same geometric pattern as Sibarist WAVE B3. Both
  // would benefit from paperShape='flat' + wallStructure='fluted' per Project
  // #2 audit item #3 (paperShape vs wallStructure decomposition). UNIQUE
  // pattern: April's bottom diameter is brewer-specific large, so it
  // operationally fits only the April brewer (like UFO paper only fits UFO
  // dripper). Geometric class (flat-bottom-fluted) ≠ brewer-fit class.
  {
    name: "April Paper Filter",
    manufacturer: "April",
    sku: "APRIL-STD",
    link: "https://www.aprilcoffeeroasters.com/collections/april-brewing-accessories/products/april-paper-filter",
    paperShape: "Flat",
    sizeStandard: "Kalita-155",
    // Fit corrected 2026-06-03 (pruning case 004): the April paper's bottom
    // diameter is brewer-specific large, so it operationally fits ONLY the April
    // brewer (not Orea/Kalita despite the shared Kalita-155 size standard) — same
    // pattern as UFO paper only fitting the UFO dripper. Prior
    // ["April","Orea","Kalita"] was wrong.
    fitsBrewers: ["April"],
    sealFitType: "Standard",
    material: "Wood pulp",
    thickness: "Medium",
    crepeStructure: "Medium",
    flowRate: "Medium",
    flowConsistency: "Stable",
    bypassInteraction: "Neutral",
    cloggingRisk: "Medium",
    clarity: "Medium",
    body: "Medium",
    sweetnessExpression: "Rounded",
    paperTechnology: "Standard",
    bestArchetype: "Stability flat",
    compatibleSystems: "April",
    owned: true,
    location: "Home",
    primaryUseCase: "Balanced flat extraction (moderate flow, neutral profile)",
  },
  {
    name: "CAFEC T-92 - Cup 4 Light Roast Paper Filter",
    displayName: "CAFEC T-92",
    manufacturer: "Cafec",
    sku: "LC4-100W",
    link: "https://cafecusa.com/collections/filter-papers/products/cafec-pour-over",
    paperShape: "Conical",
    sizeStandard: "V60-02",
    fitsBrewers: ["V60", "Origami", "Cafec"],
    sealFitType: "Standard",
    material: "Wood pulp",
    thickness: "Thin",
    crepeStructure: "High",
    flowRate: "Fast",
    flowConsistency: "Stable",
    bypassInteraction: "Promotes",
    cloggingRisk: "Low",
    clarity: "High",
    body: "Low",
    sweetnessExpression: "Clean",
    paperTechnology: "Roast-specific",
    bestArchetype: "Clarity cone",
    compatibleSystems: "V60 / Origami",
    owned: true,
    location: "Home",
    primaryUseCase: "Peak clarity (max separationm, high-acid coffees)",
    measuredDrawdownSec: 80,
    measurementDose: "15g",
    measurementBaseline: "Sibarist CONE B3 = 60s @ 15g / EG-1 6.5 / Hario V60 Glass V60-01",
    measurementDate: "2026-05-23",
    measurementProject: "cone-filter-drawdown",
    bedBehaviorUnderLoad: 'late-forming-crater',
    measurementNote: "RP4 BS re-measurement (2026-05-26): 107s vs HALO-B3 baseline 91s = +16 REAL slow. Δ-in-deltas vs P1 V60 = -4 (P1 +20 → RP4 +16; ~80% of P1 slowness persists in paper-only context). **Test 2 HOLDS** — CAFEC family is paper-fiber-real slow, not paper-brewer-interaction artifact. P1 Headline #1 conclusion holds and extends to full CAFEC Cup 4 line. Paper buckled under load without V60 dripper support (RP4-N1 — paperShapeRetention sub-attribute candidate).",
  },
  {
    name: "CAFEC T-90 - Cup 1 Medium Roast Paper Filter",
    manufacturer: "Cafec",
    sku: "MC1-100W",
    link: "https://cafecusa.com/collections/filter-papers/products/cafec-cup-1-pour-over-coffee-paper-filter-by-roasting-type-flow-rate-differences-for-specialty-coffee-medium-roast-faster-flow-rate-1-cup-size-v60-01",
    paperShape: "Conical",
    sizeStandard: "V60-01",
    fitsBrewers: ["V60", "Origami", "Cafec"],
    sealFitType: "Standard",
    material: "Wood pulp",
    thickness: "Medium",
    crepeStructure: "Medium",
    flowRate: "Medium-fast",
    flowConsistency: "Stable",
    bypassInteraction: "Neutral",
    cloggingRisk: "Medium",
    clarity: "Medium",
    body: "Medium",
    sweetnessExpression: "Rounded",
    paperTechnology: "Roast-specific",
    bestArchetype: "Stability flat (cone variant)",
    compatibleSystems: "V60 / Origami",
    // Ownership corrected 2026-05-24 (Research Project #3 prep): Chris owns
    // CAFEC papers only via the Cup 4 (V60-02) 4-pack assortment per
    // https://cafecusa.com/products/copy-of-cafec-4p-paper-filter-assortment-v60-02-cup4-cfa4-40w-4p
    // Cup 1 (V60-01) variants like this MC1 entry are not owned. Same Project #1
    // SKU naming-convention drift (1/4 digit encodes paper SIZE not roast spec).
  },
  {
    name: "CAFEC T-83 - Cup 1 Dark Roast Paper Filter",
    manufacturer: "Cafec",
    sku: "DC1-40W",
    link: "https://cafecusa.com/collections/filter-papers/products/cup-1-dark-roast-paper-filter-dc1-40w",
    paperShape: "Conical",
    sizeStandard: "V60-01",
    fitsBrewers: ["V60", "Origami", "Cafec"],
    sealFitType: "Standard",
    material: "Wood pulp",
    thickness: "Thick",
    crepeStructure: "Low",
    flowRate: "Slow",
    flowConsistency: "Stable",
    bypassInteraction: "Reduces",
    cloggingRisk: "High",
    clarity: "Low",
    body: "High",
    sweetnessExpression: "Muted",
    paperTechnology: "Roast-specific",
    bestArchetype: "Immersion hybrid (cone assist)",
    compatibleSystems: "V60 / Switch",
    // Ownership corrected 2026-05-24 (Research Project #3 prep): Chris owns
    // CAFEC papers only via the Cup 4 (V60-02) 4-pack assortment. Cup 1 (V60-01)
    // variants like this DC1 entry are not owned. Same Project #1 SKU
    // naming-convention drift.
  },
  {
    name: "CAFEC Abaca+ Cup 1 Cone Paper Filter",
    displayName: "CAFEC Abaca+ Cone",
    manufacturer: "Cafec",
    sku: "APC1-100W",
    link: "https://cafecusa.com/collections/filter-papers/products/copy-of-cafec-abaca-cup-1-cone-paper-filter-v60-01-ac1-100w",
    paperShape: "Conical",
    sizeStandard: "V60-01",
    fitsBrewers: ["V60", "Origami", "Cafec"],
    sealFitType: "Standard",
    material: "Abaca + pulp",
    thickness: "Thin",
    crepeStructure: "Medium",
    flowRate: "Fast",
    flowConsistency: "Stable",
    bypassInteraction: "Neutral",
    cloggingRisk: "Low",
    clarity: "High",
    body: "Low",
    sweetnessExpression: "Clean",
    paperTechnology: "Abaca",
    bestArchetype: "Clarity cone",
    compatibleSystems: "V60 / Origami",
  },
  {
    name: "CAFEC Abaca Cup 1 Cone Paper Filter",
    manufacturer: "Cafec",
    sku: "AC1-100W",
    link: "https://cafecusa.com/collections/filter-papers/products/cafec-abaca-coffee-paper-filter-for-specialty-coffee-1-cup",
    paperShape: "Conical",
    sizeStandard: "V60-01",
    fitsBrewers: ["V60", "Origami", "Cafec"],
    sealFitType: "Standard",
    material: "Abaca + pulp",
    thickness: "Thin",
    crepeStructure: "Medium",
    flowRate: "Fast",
    flowConsistency: "Stable",
    bypassInteraction: "Neutral",
    cloggingRisk: "Low",
    clarity: "High",
    body: "Low",
    sweetnessExpression: "Clean",
    paperTechnology: "Abaca",
    bestArchetype: "Clarity cone",
    compatibleSystems: "V60 / Origami",
  },
  {
    name: "CAFEC Abaca Cup 4 Cone Paper Filter (40 pack)",
    manufacturer: "Cafec",
    sku: "APC4-40W",
    link: "https://cafecusa.com/collections/filter-papers/products/copy-of-cafec-abaca-cup-4-cone-paper-filter-v60-02-apc4-40w",
    paperShape: "Conical",
    sizeStandard: "V60-02",
    fitsBrewers: ["V60", "Origami", "Cafec"],
    sealFitType: "Standard",
    material: "Abaca + pulp",
    thickness: "Thin",
    crepeStructure: "Medium",
    flowRate: "Fast",
    flowConsistency: "Stable",
    bypassInteraction: "Neutral",
    cloggingRisk: "Low",
    clarity: "High",
    body: "Low",
    sweetnessExpression: "Clean",
    paperTechnology: "Abaca",
    bestArchetype: "Clarity cone",
    compatibleSystems: "V60 / Origami",
    owned: true,
    location: "Home",
    primaryUseCase: "Fast clarity baseline (standard high-flow reference; owned in both 40-pack assortment and 100-pack standalone variants)",
    measuredDrawdownSec: 72,
    measurementDose: "15g",
    measurementBaseline: "Sibarist CONE B3 = 60s @ 15g / EG-1 6.5 / Hario V60 Glass V60-01",
    measurementDate: "2026-05-23",
    measurementProject: "cone-filter-drawdown",
    bedBehaviorUnderLoad: 'late-forming-crater',
    measurementNote: "RP4 BS re-measurement (2026-05-26): 108s vs HALO-B3 baseline 91s = +17 STRONGLY REAL slow. Δ-in-deltas vs P1 V60 = +5 (P1 +12 edge → RP4 +17 — hidden slowness was MASKED by P1's 8s noise floor; tighter BS 4s floor disambiguates). **Test 3 RESOLVED REAL** — APC4 has genuine paper-fiber slowness, not noise-floor-edge artifact. Same buckling pattern as LC4/DC4/MC4 (CAFEC family RP4-N1).",
  },
  {
    name: "CAFEC T-92 - Cup 1 Light Roast Paper Filter (slow)",
    manufacturer: "Cafec",
    sku: "LC1-100W",
    link: "https://cafecusa.com/collections/filter-papers/products/cafec-cup-1-pour-over-coffee-paper-filter-by-roasting-type-flow-rate-differences-for-specialty-coffee-light-roast-slower-flow-rate-1-cup-size-v60-01",
    paperShape: "Conical",
    sizeStandard: "V60-01",
    fitsBrewers: ["V60", "Origami", "Cafec"],
    sealFitType: "Standard",
    material: "Wood pulp",
    thickness: "Thin",
    crepeStructure: "High",
    flowRate: "Medium",
    flowConsistency: "Stable",
    bypassInteraction: "Promotes",
    cloggingRisk: "Low",
    clarity: "High",
    body: "Low",
    sweetnessExpression: "Clean",
    paperTechnology: "Roast-specific",
    bestArchetype: "Clarity cone",
    compatibleSystems: "V60 / Origami",
  },
  {
    name: "CAFEC Abaca+ Deep 27 Coffee Filter (white)",
    manufacturer: "Cafec",
    sku: "AFD27-100W",
    link: "https://cafecusa.com/products/copy-of-cafec-abaca-cup-4-cone-paper-filter-v60-02-ac4-100w-3",
    paperShape: "Conical (deep)",
    sizeStandard: "Deep27",
    fitsBrewers: ["Cafec Deep27", "Funnex"],
    sealFitType: "Tight (deep fit)",
    material: "Abaca+ (refined blend)",
    thickness: "Thin",
    crepeStructure: "Medium-high",
    flowRate: "Fast",
    flowConsistency: "Very stable",
    bypassInteraction: "Reduces (depth-driven)",
    cloggingRisk: "Low",
    clarity: "High",
    body: "Medium",
    sweetnessExpression: "Clean but weighted",
    paperTechnology: "Abaca",
    bestArchetype: "Clarity cone (deep extraction)",
    compatibleSystems: "Cafec Deep27 systems, Funnex",
    owned: true,
    location: "Home",
    primaryUseCase: "Deep extraction clarity (increase contact time via bed depth, not resistance)",
    measuredDrawdownSec: 144,
    measurementDose: "10g",
    measurementBaseline: "Sibarist CONE 28 FAST (Project #3a baseline; bimodal — slow regime 131s, fast regime 31.5s, ~80/20 split)",
    measurementDate: "2026-05-25",
    measurementProject: "specialty-cone-filter-drawdown",
    bedBehaviorUnderLoad: 'late-forming-crater',
    measurementNote: "Tested in Funnex (deep cone). Landed in slow regime; +13s vs slow-regime baseline = FE within regime. All three #3a non-baseline papers were FE to baseline within their respective regimes — practical paper-paper differentiation in Funnex is which regime each lands in (paper-geometry × brewer-geometry interaction, Lesson #26 fold-geometry → bed-shape).",
  },
  {
    name: "CAFEC Abaca Cup 4 Cone Paper Filter",
    manufacturer: "Cafec",
    sku: "AC4-100W",
    link: "https://cafecusa.com/collections/filter-papers/products/cafec-abaca-coffee-paper-filter-for-specialty-coffee",
    paperShape: "Conical",
    sizeStandard: "V60-02",
    fitsBrewers: ["V60", "Origami", "Cafec", "Orea Apex"],
    sealFitType: "Standard",
    material: "Abaca + pulp",
    thickness: "Thin",
    crepeStructure: "Medium",
    flowRate: "Fast",
    flowConsistency: "Stable",
    bypassInteraction: "Neutral",
    cloggingRisk: "Low",
    clarity: "High",
    body: "Low",
    sweetnessExpression: "Clean",
    paperTechnology: "Abaca",
    bestArchetype: "Clarity cone",
    compatibleSystems: "V60 / Origami / Orea Apex",
  },
  {
    name: "CAFEC Cup 4 Medium Roast Paper Filter",
    manufacturer: "Cafec",
    sku: "MC4-100W",
    link: "https://cafecusa.com/collections/filter-papers/products/copy-of-cafec-cup-4-medium-roast-paper-filter-v60-02-mc4-100w-2",
    paperShape: "Conical",
    sizeStandard: "V60-02",
    fitsBrewers: ["V60", "Origami", "Cafec"],
    sealFitType: "Standard",
    material: "Wood pulp",
    thickness: "Medium",
    crepeStructure: "Medium",
    flowRate: "Medium-fast",
    flowConsistency: "Stable",
    bypassInteraction: "Neutral",
    cloggingRisk: "Medium",
    clarity: "Medium",
    body: "Medium",
    sweetnessExpression: "Rounded",
    paperTechnology: "Roast-specific",
    bestArchetype: "Stability flat (cone variant)",
    compatibleSystems: "V60 / Origami",
    owned: true,
    location: "Home",
    primaryUseCase: "Owned via Cafec 4-pack assortment (40-pack variant); medium-roast specific",
    measuredDrawdownSec: 60,
    measurementDose: "15g",
    measurementBaseline: "Sibarist CONE B3 = 60s @ 15g / EG-1 6.5 / Hario V60 Glass V60-01",
    measurementDate: "2026-05-23",
    measurementProject: "cone-filter-drawdown",
    bedBehaviorUnderLoad: 'mixed',
    measurementNote: "RP4 BS re-measurement (2026-05-26): 98s vs HALO-B3 baseline 91s = +7 REAL slow (modest). Δ-in-deltas vs P1 V60 = +7 — third CAFEC noise-floor reveal (P1 read MC4 as 0 baseline-equivalent; BS reveals +7 paper-fiber slowness was hidden). CAFEC family slow pattern confirmed at 3-of-4 sample (DC4 +11 / MC4 +7 / APC4 +5; LC4 -4 already-classified-real in P1). RP4 AI-3 queued: add CAFEC T-code productCode field (this entry's T-code = T-90).",
  },
  {
    name: "CAFEC Cup 4 Dark Roast Paper Filter",
    manufacturer: "Cafec",
    sku: "DC4-100W",
    link: "https://cafecusa.com/collections/filter-papers/products/copy-of-cafec-cup-4-dark-roast-paper-filter-v60-02-dc4-100w",
    paperShape: "Conical",
    sizeStandard: "V60-02",
    fitsBrewers: ["V60", "Origami", "Cafec"],
    sealFitType: "Standard",
    material: "Wood pulp",
    thickness: "Thick",
    crepeStructure: "Low",
    flowRate: "Slow",
    flowConsistency: "Stable",
    bypassInteraction: "Reduces",
    cloggingRisk: "High",
    clarity: "Low",
    body: "High",
    sweetnessExpression: "Muted",
    paperTechnology: "Roast-specific",
    bestArchetype: "Immersion hybrid (cone assist)",
    compatibleSystems: "V60 / Switch / Clever",
    owned: true,
    location: "Home",
    primaryUseCase: "Owned via Cafec 4-pack assortment (40-pack variant); dark-roast specific. NOTE: measured drawdown (68s) contradicts registry flowRate 'Slow' + thickness 'Thick' cells. See cone-filter-drawdown.md for the Cafec roast-specific paper finding.",
    measuredDrawdownSec: 68,
    measurementDose: "15g",
    measurementBaseline: "Sibarist CONE B3 = 60s @ 15g / EG-1 6.5 / Hario V60 Glass V60-01",
    measurementDate: "2026-05-23",
    measurementProject: "cone-filter-drawdown",
    bedBehaviorUnderLoad: 'late-forming-crater',
    measurementNote: "RP4 BS re-measurement (2026-05-26): 110s vs HALO-B3 baseline 91s = +19 REAL slow. Δ-in-deltas vs P1 V60 = +11 — **MAJOR REVEAL**: DC4 read as P1 indistinguishable (+7-8) but tighter BS floor exposed +11s of hidden paper-fiber slowness. **Test 2 REINFORCED** — CAFEC Cup 4 family uniformly paper-fiber-slow. P1 Headline #1 conclusion EXTENDS to T-83 dark roast: registry labels = extraction-engineering semantics, NOT flow-rate semantics. Lesson #36 is family-conditional, not universal (RP4-N4). RP4 AI-3: T-code = T-83.",
  },
  {
    name: "CAFEC Abaca Trapezoid Filter 102",
    manufacturer: "Cafec",
    sku: "AB-102-100W",
    link: "https://cafecusa.com/collections/filter-papers/products/cafec-102-abaca-trapezoid-paper-filter-for-3-5-cups-100pcs-pack-disposable-pour-over-drip-coffee-paper-filter-made-of-eco-friendly-refined-virgin-pulp-for-better-tasting-brewing-pour-over-dripper-white",
    paperShape: "Trapezoid",
    sizeStandard: "102",
    fitsBrewers: ["Clever", "Melitta", "OXO", "Cafec Oval"],
    sealFitType: "Standard",
    material: "Abaca + pulp",
    thickness: "Thin",
    crepeStructure: "Medium",
    flowRate: "Fast",
    flowConsistency: "Stable",
    bypassInteraction: "Neutral",
    cloggingRisk: "Low",
    clarity: "High",
    body: "Low",
    sweetnessExpression: "Clean",
    paperTechnology: "Abaca",
    bestArchetype: "Stability flat",
    compatibleSystems: "Trapezoid systems",
  },
  {
    name: "CAFEC Abaca Trapezoid Filter 101",
    manufacturer: "Cafec",
    sku: "AB-101-100W",
    link: "https://cafecusa.com/collections/filter-papers/products/cafec-101-abaca-trapezoid-paper-filter-for-1-3-cups-100pcs-pack-disposable-pour-over-drip-coffee-paper-filter-made-of-eco-friendly-refined-virgin-pulp-for-better-tasting-brewing-pour-over-dripper-white",
    paperShape: "Trapezoid",
    sizeStandard: "101",
    fitsBrewers: ["Clever", "Melitta (small)", "Cafec Oval"],
    sealFitType: "Standard",
    material: "Abaca + pulp",
    thickness: "Thin",
    crepeStructure: "Medium",
    flowRate: "Fast",
    flowConsistency: "Stable",
    bypassInteraction: "Neutral",
    cloggingRisk: "Low",
    clarity: "High",
    body: "Low",
    sweetnessExpression: "Clean",
    paperTechnology: "Abaca",
    bestArchetype: "Stability flat",
    compatibleSystems: "Trapezoid systems",
  },
  {
    name: "CAFEC Abaca Trapezoid Filter 102 (Alt SKU)",
    manufacturer: "Cafec",
    sku: "AB-102-100W",
    link: "https://cafecusa.com/collections/filter-papers/products/copy-of-cafec-trapezoid-102-cup-3-5-abaca-trapezoid-paper-filter-ab-102-100w",
    paperShape: "Trapezoid",
    sizeStandard: "102",
    fitsBrewers: ["Clever", "Melitta", "OXO", "Cafec Oval"],
    sealFitType: "Standard",
    material: "Abaca + pulp",
    thickness: "Thin",
    crepeStructure: "Medium",
    flowRate: "Fast",
    flowConsistency: "Stable",
    bypassInteraction: "Neutral",
    cloggingRisk: "Low",
    clarity: "High",
    body: "Low",
    sweetnessExpression: "Clean",
    paperTechnology: "Abaca",
    bestArchetype: "Stability flat",
    compatibleSystems: "Trapezoid systems",
  },
  {
    name: "CAFEC SFP Cup 4 Cone Paper Filter",
    manufacturer: "Cafec",
    sku: "SFP4-100W",
    link: "https://cafecusa.com/collections/filter-papers/products/sfp-cup-4-cone-paper-filter-sfp4-100w",
    paperShape: "Conical",
    sizeStandard: "V60-02",
    fitsBrewers: ["V60", "Origami", "Cafec"],
    sealFitType: "Tight (low bypass)",
    material: "Refined pulp",
    thickness: "Medium",
    crepeStructure: "High",
    flowRate: "Medium",
    flowConsistency: "Very stable",
    bypassInteraction: "Reduces",
    cloggingRisk: "Low",
    clarity: "High",
    body: "Medium",
    sweetnessExpression: "Clean",
    paperTechnology: "Structured",
    bestArchetype: "Clarity cone (controlled)",
    compatibleSystems: "V60 / Origami",
  },
  {
    name: "CAFEC Traditional Cup 1 Filter",
    manufacturer: "Cafec",
    sku: "CC1-100W",
    link: "https://cafecusa.com/collections/filter-papers/products/cafec-cup-1-traditional-paper-filter-cc1-100w",
    paperShape: "Conical",
    sizeStandard: "V60-01",
    fitsBrewers: ["V60", "Origami", "Cafec"],
    sealFitType: "Loose",
    material: "Wood pulp",
    thickness: "Medium",
    crepeStructure: "Low",
    flowRate: "Medium",
    flowConsistency: "Variable",
    bypassInteraction: "Promotes",
    cloggingRisk: "Medium",
    clarity: "Medium",
    body: "Medium",
    sweetnessExpression: "Rounded",
    paperTechnology: "Standard",
    bestArchetype: "Clarity cone (classic)",
    compatibleSystems: "V60 / Origami",
  },
  {
    name: "CAFEC Arita Ware Paper Filter",
    manufacturer: "Cafec",
    sku: "DDF-100W",
    link: "https://cafecusa.com/collections/filter-papers/products/copy-of-cafec-arita-ware-paper-filter-ddf-100w",
    paperShape: "Conical",
    sizeStandard: "V60-02",
    fitsBrewers: ["V60", "Origami", "Cafec"],
    sealFitType: "Tight (low bypass)",
    material: "Refined pulp",
    thickness: "Medium",
    crepeStructure: "High",
    flowRate: "Medium",
    flowConsistency: "Very stable",
    bypassInteraction: "Reduces",
    cloggingRisk: "Low",
    clarity: "High",
    body: "Medium",
    sweetnessExpression: "Clean",
    paperTechnology: "Structured",
    bestArchetype: "Clarity cone (controlled)",
    compatibleSystems: "V60 / Origami",
  },
  {
    name: "CAFEC Abaca Cup 4 Cone Paper Filter (brown 40)",
    manufacturer: "Cafec",
    sku: "AC4-40B",
    link: "https://cafecusa.com/collections/filter-papers/products/abaca-cup-4-cone-paper-filter-ac4-40b",
    paperShape: "Conical",
    sizeStandard: "V60-02",
    fitsBrewers: ["V60", "Origami", "Cafec"],
    sealFitType: "Standard",
    material: "Abaca + pulp (unbleached)",
    thickness: "Thin",
    crepeStructure: "Medium",
    flowRate: "Fast",
    flowConsistency: "Stable",
    bypassInteraction: "Neutral",
    cloggingRisk: "Low",
    clarity: "High",
    body: "Low",
    sweetnessExpression: "Clean",
    paperTechnology: "Abaca",
    bestArchetype: "Clarity cone",
    compatibleSystems: "V60 / Origami",
  },
  {
    name: "CAFEC Abaca Cup 4 Cone Paper Filter (brown 100)",
    manufacturer: "Cafec",
    sku: "AC4-100B",
    link: "https://cafecusa.com/collections/filter-papers/products/abaca-cup-4-cone-paper-filter-ac4-100b",
    paperShape: "Conical",
    sizeStandard: "V60-02",
    fitsBrewers: ["V60", "Origami", "Cafec"],
    sealFitType: "Standard",
    material: "Abaca + pulp (unbleached)",
    thickness: "Thin",
    crepeStructure: "Medium",
    flowRate: "Fast",
    flowConsistency: "Stable",
    bypassInteraction: "Neutral",
    cloggingRisk: "Low",
    clarity: "High",
    body: "Low",
    sweetnessExpression: "Clean",
    paperTechnology: "Abaca",
    bestArchetype: "Clarity cone",
    compatibleSystems: "V60 / Origami",
  },
  {
    name: "CAFEC Wave Paper Filter 250",
    manufacturer: "Cafec",
    sku: "WF250-250W",
    link: "https://cafecusa.com/collections/filter-papers/products/cafec-wave-paper-filters-250-no-250-wave-filter-250-sheets-bag-4-bags-per-carton-wf250-250w",
    paperShape: "Wave",
    sizeStandard: "Kalita-185",
    fitsBrewers: ["Kalita", "Orea", "April", "Stagg"],
    sealFitType: "Standard",
    material: "Wood pulp",
    thickness: "Medium",
    crepeStructure: "Medium",
    flowRate: "Medium",
    flowConsistency: "Stable",
    bypassInteraction: "Neutral",
    cloggingRisk: "Medium",
    clarity: "Medium",
    body: "Medium",
    sweetnessExpression: "Rounded",
    paperTechnology: "Standard",
    bestArchetype: "Stability flat",
    compatibleSystems: "Kalita / Orea / April",
  },
  {
    name: "CAFEC Abaca Cup 4 Cone Paper Filter (variant)",
    manufacturer: "Cafec",
    sku: "AC4-100W",
    link: "https://cafecusa.com/collections/filter-papers/products/copy-of-cafec-abaca-cup-4-cone-paper-filter-v60-02-ac4-100w-3",
    paperShape: "Conical",
    sizeStandard: "V60-02",
    fitsBrewers: ["V60", "Origami", "Cafec"],
    sealFitType: "Standard",
    material: "Abaca + pulp",
    thickness: "Thin",
    crepeStructure: "Medium",
    flowRate: "Fast",
    flowConsistency: "Stable",
    bypassInteraction: "Neutral",
    cloggingRisk: "Low",
    clarity: "High",
    body: "Low",
    sweetnessExpression: "Clean",
    paperTechnology: "Abaca",
    bestArchetype: "Clarity cone",
    compatibleSystems: "V60 / Origami",
  },
  {
    name: "CAFEC TH-1 Light Roast Paper Filter",
    manufacturer: "Cafec",
    sku: "TH1-4-100",
    link: "https://cafecusa.com/collections/filter-papers/products/cafec-th-1-cup-4-light-roast-paper-filter-v60-02-th14-100-copy",
    paperShape: "Conical",
    sizeStandard: "V60-02",
    fitsBrewers: ["V60", "Origami", "Cafec"],
    sealFitType: "Tight (low bypass)",
    material: "Refined pulp",
    thickness: "Thin",
    crepeStructure: "High",
    flowRate: "Fast",
    flowConsistency: "Very stable",
    bypassInteraction: "Reduces",
    cloggingRisk: "Low",
    clarity: "High",
    body: "Low",
    sweetnessExpression: "Clean",
    paperTechnology: "Structured",
    bestArchetype: "Clarity cone (controlled)",
    compatibleSystems: "V60 / Origami",
  },
  {
    name: "CAFEC TH-3 Medium Roast Paper Filter",
    manufacturer: "Cafec",
    sku: "TH3-4-100",
    link: "https://cafecusa.com/collections/filter-papers/products/cafec-th-3-cup-4-medium-roast-paper-filter-v60-02-th34-100-copy",
    paperShape: "Conical",
    sizeStandard: "V60-02",
    fitsBrewers: ["V60", "Origami", "Cafec"],
    sealFitType: "Tight (low bypass)",
    material: "Refined pulp",
    thickness: "Medium",
    crepeStructure: "High",
    flowRate: "Medium-fast",
    flowConsistency: "Very stable",
    bypassInteraction: "Reduces",
    cloggingRisk: "Low",
    clarity: "Medium",
    body: "Medium",
    sweetnessExpression: "Rounded",
    paperTechnology: "Structured",
    bestArchetype: "Stability flat (cone variant)",
    compatibleSystems: "V60 / Origami",
  },
  {
    name: "CAFEC TH-2 Dark Roast Paper Filter",
    manufacturer: "Cafec",
    sku: "TH2-4-100",
    link: "https://cafecusa.com/collections/filter-papers/products/cafec-th-2-cup-4-dark-roast-paper-filter-v60-02-th24-100-copy",
    paperShape: "Conical",
    sizeStandard: "V60-02",
    fitsBrewers: ["V60", "Origami", "Cafec"],
    sealFitType: "Tight (low bypass)",
    material: "Refined pulp",
    thickness: "Thick",
    crepeStructure: "High",
    flowRate: "Slow",
    flowConsistency: "Very stable",
    bypassInteraction: "Reduces",
    cloggingRisk: "Low",
    clarity: "Low",
    body: "High",
    sweetnessExpression: "Muted",
    paperTechnology: "Structured",
    bestArchetype: "Immersion hybrid (cone assist)",
    compatibleSystems: "V60 / Switch / Clever",
  },
  {
    name: "CAFEC Abaca Trapezoid Filter 101 (variant)",
    manufacturer: "Cafec",
    sku: "AB-101-100W",
    link: "https://cafecusa.com/collections/filter-papers/products/cafec-trapezoid-101-abaca-trapezoid-paper-filter-for-1-2-cups-100pcs-pack-ab-101-100w-copy",
    paperShape: "Trapezoid",
    sizeStandard: "101",
    fitsBrewers: ["Clever", "Melitta (small)", "Cafec Oval"],
    sealFitType: "Standard",
    material: "Abaca + pulp",
    thickness: "Thin",
    crepeStructure: "Medium",
    flowRate: "Fast",
    flowConsistency: "Stable",
    bypassInteraction: "Neutral",
    cloggingRisk: "Low",
    clarity: "High",
    body: "Low",
    sweetnessExpression: "Clean",
    paperTechnology: "Abaca",
    bestArchetype: "Stability flat",
    compatibleSystems: "Trapezoid systems",
  },
  {
    name: "Chemex Bonded Filter (Half Moon White)",
    manufacturer: "Chemex",
    sku: "CHEMEX-HM-W",
    link: "https://chemexcoffeemaker.com/products/chemex-bonded-filters-unfolded-half-moon",
    paperShape: "Conical (folded)",
    sizeStandard: "Chemex",
    fitsBrewers: ["Funnex", "Chemex"],
    sealFitType: "Loose (thick seal via paper; paper sits ABOVE Funnex rim per Project #3 Lesson #25 physical constraint — see AI-1 paperFitsBrewerRim registry field proposal)",
    material: "Bonded pulp",
    thickness: "Very thick",
    crepeStructure: "Low",
    flowRate: "Slow (registry, partial-seal confound suspected per Project #3 AI-5) / FE within Funnex slow regime per Project #3a measurement",
    flowConsistency: "Very stable",
    bypassInteraction: "Strongly reduces",
    cloggingRisk: "High",
    clarity: "High",
    body: "Very high",
    sweetnessExpression: "Heavy",
    paperTechnology: "Standard",
    bestArchetype: "Clarity cone (low bypass)",
    compatibleSystems: "Chemex / Funnex",
    owned: true,
    location: "Home",
    primaryUseCase: "Use as immersion-like cone (max body + filtration, suppresses brightness)",
    measuredDrawdownSec: 118,
    measurementDose: "10g",
    measurementBaseline: "Sibarist CONE 28 FAST (Project #3a baseline; bimodal)",
    measurementDate: "2026-05-25",
    measurementProject: "specialty-cone-filter-drawdown",
    bedBehaviorUnderLoad: 'late-forming-crater',
    measurementNote: "Tested in Funnex (deep cone, cone-fold manual). Landed in slow regime; -13s vs slow-regime baseline = FE within regime. REGISTRY-DRIFT AUDIT (AI-5): registry flowRate 'Slow' but measured FE to baseline in Funnex — partial-seal confound possible (thicker paper may have produced lighter seal than CONE28-FAST baseline). Cone-fold creates deep narrow bed in Funnex; FS-100's fan-fold (factory pre-folded squares) creates wider shallower bed and drains 73s faster (45s vs 118s) on same Chemex bonded pulp fiber. Demonstrates Lesson #26 (bed-shape from fold geometry as throughput determinant).",
  },
  {
    name: "Chemex Bonded Filter (Half Moon Natural)",
    manufacturer: "Chemex",
    sku: "CHEMEX-HM-N",
    link: "https://chemexcoffeemaker.com/products/chemex-bonded-filters-unfolded-half-moon-natural",
    paperShape: "Conical (folded)",
    sizeStandard: "Chemex",
    fitsBrewers: ["Funnex", "Chemex"],
    sealFitType: "Loose (thick seal via paper)",
    material: "Bonded pulp (unbleached)",
    thickness: "Very thick",
    crepeStructure: "Low",
    flowRate: "Slow",
    flowConsistency: "Very stable",
    bypassInteraction: "Strongly reduces",
    cloggingRisk: "High",
    clarity: "High",
    body: "Very high",
    sweetnessExpression: "Heavy",
    paperTechnology: "Standard",
    bestArchetype: "Clarity cone (low bypass)",
    compatibleSystems: "Chemex / Funnex",
  },
  {
    // Net-new entry surfaced at Project #3 Step 0 photo confirmation (2026-05-25).
    // Demonstrates Lesson #26 (bed-shape from fold geometry as throughput determinant):
    // same Chemex bonded pulp fiber + same thickness as CHEMEX-HM-W but 73s faster
    // drawdown in Funnex (45s vs 118s) due to fan-fold (wider shallower bed) vs
    // cone-fold (deep narrow bed).
    name: "Chemex Bonded Pre-folded Squares (White)",
    manufacturer: "Chemex",
    sku: "FS-100",
    link: "https://chemexcoffeemaker.com/products/chemex-bonded-pre-folded-squares-100ct",
    paperShape: "Square (pre-folded)",
    sizeStandard: "Chemex",
    fitsBrewers: ["Funnex", "Chemex"],
    sealFitType: "Loose (factory fan-fold; paper sits ABOVE Funnex rim per Project #3 Lesson #25 physical constraint)",
    material: "Bonded pulp",
    thickness: "Very thick",
    crepeStructure: "Low (factory fan-fold)",
    flowRate: "Fast (in Funnex; 73s faster than CHEMEX-HM-W cone-fold on same fiber per Project #3 Lesson #26)",
    flowConsistency: "Very stable",
    bypassInteraction: "Reduces",
    cloggingRisk: "Medium",
    clarity: "High",
    body: "Medium",
    sweetnessExpression: "Clean",
    paperTechnology: "Standard (pre-folded squares)",
    bestArchetype: "Clarity cone (fast)",
    compatibleSystems: "Chemex / Funnex",
    owned: true,
    location: "Home",
    primaryUseCase: "Fan-fold flat-bed alternative to Chemex cone-fold; faster drawdown in deep cone brewers (Funnex) due to wider/shallower bed geometry",
    measuredDrawdownSec: 45,
    measurementDose: "10g",
    measurementBaseline: "Sibarist CONE 28 FAST (Project #3a baseline; bimodal — slow regime 131s, fast regime 31.5s)",
    measurementDate: "2026-05-25",
    measurementProject: "specialty-cone-filter-drawdown",
    bedBehaviorUnderLoad: 'late-forming-crater',
    measurementNote: "Fan-fold factory pre-folded squares create wider shallower bed in Funnex vs CHEMEX-HM-W's manual cone-fold deep narrow bed. Same Chemex bonded pulp fiber + same thickness as HM-W but 73s drawdown spread (45s vs 118s). Demonstrates Lesson #26 (bed-shape from fold geometry as throughput determinant). Landed in fast regime under bimodal interpretation; +13.5s vs fast-regime baseline = FE within regime. Net-new registry entry surfaced at Step 0 photo confirmation — single most impactful Step 0 finding in #3.",
  },
  {
    name: "Hario V60 Paper Filter 01 (Tabbed)",
    manufacturer: "Hario",
    sku: "VCF-01-100W",
    link: "https://www.hario-usa.com/products/paper-filter-for-01-drippers",
    paperShape: "Conical",
    sizeStandard: "V60-01",
    fitsBrewers: ["V60", "Origami"],
    sealFitType: "Loose",
    material: "Wood pulp",
    thickness: "Medium",
    crepeStructure: "Low",
    flowRate: "Medium",
    flowConsistency: "Variable",
    bypassInteraction: "Promotes",
    cloggingRisk: "Medium",
    clarity: "Medium",
    body: "Medium",
    sweetnessExpression: "Rounded",
    paperTechnology: "Standard",
    bestArchetype: "Clarity cone (classic)",
    compatibleSystems: "V60 / Origami",
    owned: true,
    location: "Home",
    primaryUseCase: "Baseline cone reference (introduces variability intentionally)",
    measuredDrawdownSec: 65,
    measurementDose: "15g",
    measurementBaseline: "Sibarist CONE B3 = 60s @ 15g / EG-1 6.5 / Hario V60 Glass V60-01",
    measurementDate: "2026-05-23",
    measurementProject: "cone-filter-drawdown",
    bedBehaviorUnderLoad: 'pour-impact-crater',
    measurementNote: "RP4 BS re-measurement (2026-05-26): 95s vs HALO-B3 baseline 91s = +4 indistinguishable (edge). Δ-in-deltas vs P1 V60 = -1 — tracks baseline both contexts; cross-confirms METEOR-02. Hario family validates Lesson #36 paper-brewer-INTERACTION dominance. **Egg-shape bed asymmetry observed but no flow-rate impact (RP4-N6)** — surfaces 'asymmetric-stable' enum value candidate distinct from 'stable'. Buckled under load (RP4-N1, same pattern as CAFEC family) but still baseline.",
  },
  {
    name: "Hario V60 Paper Filter 01 (Untabbed)",
    manufacturer: "Hario",
    sku: "VCF-01-100M",
    link: "https://www.hario-usa.com/products/copy-of-paper-filter-for-01-drippers",
    paperShape: "Conical",
    sizeStandard: "V60-01",
    fitsBrewers: ["V60", "Origami"],
    sealFitType: "Loose",
    material: "Wood pulp",
    thickness: "Medium",
    crepeStructure: "Low",
    flowRate: "Medium",
    flowConsistency: "Variable",
    bypassInteraction: "Promotes",
    cloggingRisk: "Medium",
    clarity: "Medium",
    body: "Medium",
    sweetnessExpression: "Rounded",
    paperTechnology: "Standard",
    bestArchetype: "Clarity cone (classic)",
    compatibleSystems: "V60 / Origami",
  },
  {
    name: "Hario V60 Meteor Filter 02",
    manufacturer: "Hario",
    sku: "METEOR-02",
    link: "https://www.hario-usa.com/products/v60-meteor-filters-02",
    paperShape: "Conical",
    sizeStandard: "V60-02",
    fitsBrewers: ["V60", "Origami"],
    sealFitType: "Standard (improved seal)",
    material: "Refined pulp",
    thickness: "Thin",
    crepeStructure: "High",
    flowRate: "Fast",
    flowConsistency: "More stable",
    bypassInteraction: "Reduces",
    cloggingRisk: "Low",
    clarity: "High",
    body: "Low",
    sweetnessExpression: "Clean",
    paperTechnology: "Standard+",
    bestArchetype: "Clarity cone",
    compatibleSystems: "V60 / Origami",
    owned: true,
    location: "Home",
    primaryUseCase: "Improved clarity baseline (faster, more stable than standard Hario)",
    measuredDrawdownSec: 65,
    measurementDose: "15g",
    measurementBaseline: "Sibarist CONE B3 = 60s @ 15g / EG-1 6.5 / Hario V60 Glass V60-01",
    measurementDate: "2026-05-23",
    measurementProject: "cone-filter-drawdown",
    bedBehaviorUnderLoad: 'late-forming-crater',
    measurementNote: "RP4 BS re-measurement (2026-05-26): 93s vs HALO-B3 baseline 91s = +2 indistinguishable. Δ-in-deltas vs P1 V60 = -3 — tracks baseline both contexts (Test 1 convergence). Paper sat well above BS rim (paper edge near BS middle cylinder but NOT contacting) but no drawdown impact — strengthens RP4-N7 (above-rim seating non-impacting on flow in BS architecture) and Lesson #39 (BS as paper-only measurement platform). Hario family validates Lesson #36 paper-brewer-INTERACTION dominance.",
  },
  {
    name: "Hario V60 Paper Filter 03",
    manufacturer: "Hario",
    sku: "VCF-03-100W",
    link: "https://www.hario-usa.com/products/paper-filter-for-03-drippers",
    paperShape: "Conical",
    sizeStandard: "V60-03",
    fitsBrewers: ["V60 (large brews)"],
    sealFitType: "Loose",
    material: "Wood pulp",
    thickness: "Medium",
    crepeStructure: "Low",
    flowRate: "Medium",
    flowConsistency: "Variable",
    bypassInteraction: "Promotes",
    cloggingRisk: "Medium",
    clarity: "Medium",
    body: "Medium",
    sweetnessExpression: "Rounded",
    paperTechnology: "Standard",
    bestArchetype: "Clarity cone (classic)",
    compatibleSystems: "V60",
  },
  {
    name: "Hario Flow Paper Filters",
    manufacturer: "Hario",
    sku: "FLOW-50",
    link: "https://www.hario-usa.com/products/flow-paper-filters-50ct",
    paperShape: "Wave",
    sizeStandard: "Kalita-155",
    fitsBrewers: ["Hario Flow", "flat brewers"],
    sealFitType: "Tight (center-supported)",
    material: "Refined pulp",
    thickness: "Thin",
    crepeStructure: "Engineered",
    flowRate: "Fast",
    flowConsistency: "Very stable",
    bypassInteraction: "Reduces",
    cloggingRisk: "Low",
    clarity: "High",
    body: "Low",
    sweetnessExpression: "Clean",
    paperTechnology: "Standard+",
    bestArchetype: "Stability flat",
    compatibleSystems: "Hario Flow / Orea / Kalita",
  },
  {
    name: "Kalita Wave 155 Filter",
    manufacturer: "Kalita",
    sku: "KW155-100",
    link: "https://kalitausa.com/products/kalita-wave-155-filter-100ct",
    paperShape: "Wave",
    sizeStandard: "Kalita-155",
    fitsBrewers: ["Kalita", "Orea", "April"],
    sealFitType: "Standard",
    material: "Wood pulp",
    thickness: "Medium",
    crepeStructure: "Medium",
    flowRate: "Medium",
    flowConsistency: "Moderately stable",
    bypassInteraction: "Neutral",
    cloggingRisk: "Medium",
    clarity: "Medium",
    body: "Medium",
    sweetnessExpression: "Rounded",
    paperTechnology: "Standard",
    bestArchetype: "Stability flat",
    compatibleSystems: "Kalita / Orea / April",
  },
  {
    name: "CONE FAST",
    manufacturer: "Sibarist",
    sku: "CONE-FAST",
    link: "https://sibarist.coffee/en-es/products/cone",
    paperShape: "Conical",
    sizeStandard: "V60-02",
    fitsBrewers: ["V60", "Origami", "Orea Apex"],
    sealFitType: "Tight (precision fit)",
    material: "Specialty fiber (FAST)",
    thickness: "Ultra-thin",
    crepeStructure: "Engineered low resistance",
    flowRate: "Very fast",
    flowConsistency: "Extremely stable",
    bypassInteraction: "Neutral",
    cloggingRisk: "Very low",
    clarity: "Very high",
    body: "Low",
    sweetnessExpression: "Clean",
    paperTechnology: "FAST",
    bestArchetype: "Clarity cone",
    compatibleSystems: "V60 / Origami / Orea Apex",
    owned: true,
    location: "Home",
    primaryUseCase: "Maximum clarity ceiling (fastest stable cone extraction)",
    measuredDrawdownSec: 45,
    measurementDose: "15g",
    measurementBaseline: "Sibarist CONE B3 = 60s @ 15g / EG-1 6.5 / Hario V60 Glass V60-01",
    measurementDate: "2026-05-23",
    measurementProject: "cone-filter-drawdown",
    bedBehaviorUnderLoad: 'pour-impact-crater',
    measurementNote: "RP4 (2026-05-26): NOT TESTED in Sibarist BS — small size variant (Chris's owned variant) doesn't fit BS; cohort dropped 8→7 at Step 0. **RP4 AI-6 queued**: Sibarist FAST size variants (small vs large) worth registry sub-SKU treatment (`sizeVariant` field OR split SKUs).",
  },
  {
    name: "CONE B3",
    manufacturer: "Sibarist",
    sku: "CONE-B3",
    link: "https://sibarist.coffee/en-es/products/cone",
    paperShape: "Conical",
    sizeStandard: "V60-02",
    fitsBrewers: ["V60", "Origami", "Orea Apex"],
    sealFitType: "Tight (precision fit)",
    material: "Specialty fiber (B3)",
    thickness: "Medium",
    crepeStructure: "Engineered high structure",
    flowRate: "Medium",
    flowConsistency: "Extremely stable",
    bypassInteraction: "Reduces",
    cloggingRisk: "Very low",
    clarity: "High",
    body: "Medium",
    sweetnessExpression: "Structured",
    paperTechnology: "B3",
    bestArchetype: "Clarity cone (controlled)",
    compatibleSystems: "V60 / Origami",
    owned: true,
    location: "Home",
    primaryUseCase: "Structured clarity (adds body without sacrificing cleanliness)",
    measuredDrawdownSec: 60,
    measurementDose: "15g",
    measurementBaseline: "Self (Research Project #1 baseline; 3-replicate median, 8s range across pulls)",
    measurementDate: "2026-05-23",
    measurementProject: "cone-filter-drawdown",
    bedBehaviorUnderLoad: 'late-forming-crater',
    measurementNote: "RP4 BS re-measurement (2026-05-26): 92s vs HALO-B3 baseline 91s = +1s indistinguishable. Δ-in-deltas vs P1 V60 = +1 — cleanly tracks baseline both contexts (Lesson #36 paper-brewer-INTERACTION dominance validates for Sibarist-family papers). Cleanest Test 1 (convergence) anchor in RP4. See paper-only-v60-cohort-drawdown.md.",
  },
  {
    name: "CONE 28 FAST",
    manufacturer: "Sibarist",
    sku: "CONE28-FAST",
    link: "https://sibarist.coffee/en-es/products/cone-28-30%C2%BA",
    paperShape: "Conical",
    sizeStandard: "Low-angle cone",
    fitsBrewers: ["Deep cone brewers"],
    sealFitType: "Tight (manual crease required as Negotiator-equivalent in Funnex; see Project #3 Lesson #22 — seal-aggressiveness 36s dynamic range)",
    material: "Specialty fiber (FAST)",
    thickness: "Ultra-thin",
    crepeStructure: "Engineered",
    flowRate: "Very fast (BIMODAL in Funnex: slow regime ~131s, fast regime ~31.5s, ~80/20 split — see Project #3 Lesson #29 and #36 mechanism refinement)",
    flowConsistency: "Extremely stable (within-regime; 3s range fast regime, 36s range slow regime under bimodal interpretation in Funnex; tight noise floor recovered in Sibarist BS architecture)",
    bypassInteraction: "Neutral",
    cloggingRisk: "Very low",
    clarity: "Very high",
    body: "Low",
    sweetnessExpression: "Clean",
    paperTechnology: "FAST",
    bestArchetype: "Clarity cone",
    compatibleSystems: "Low-angle brewers, Funnex",
    owned: true,
    location: "Home",
    primaryUseCase: "Extreme extraction clarity (deep cone + high flow, high extraction yield)",
    measuredDrawdownSec: 131,
    measurementDose: "10g",
    measurementBaseline: "Self (Research Project #3a baseline; BIMODAL — slow regime median 131s range 36s across 4 reps, fast regime median 31.5s range 3s across 2 reps; ~80/20 split empirically)",
    measurementDate: "2026-05-25",
    measurementProject: "specialty-cone-filter-drawdown",
    bedBehaviorUnderLoad: 'mixed',
    measurementNote: "BIMODAL DRAWDOWN in Funnex — paper-brewer-interaction artifact per Lesson #36 (initially interpreted as paper-fiber-intrinsic self-choke per Lesson #27; refined post-#3b after HALO-B3 paper-only test showed no choke in Sibarist BS architecture). Regime selection driven by pour rate × bed throughput interaction (Lesson #31). Manual creasing as Negotiator-equivalent procedural primitive (Lesson #22). Funnex/Booster fit = NONE empirically (V60-geometry Boosters don't seat on Funnex deep cone).",
  },
  {
    name: "FLAT FAST",
    manufacturer: "Sibarist",
    sku: "FLAT-FAST",
    link: "https://sibarist.coffee/en-es/products/flat",
    paperShape: "Flat",
    sizeStandard: "Kalita-155/185",
    fitsBrewers: ["Orea", "Kalita", "April"],
    sealFitType: "Tight (low bypass)",
    material: "Specialty fiber (FAST)",
    thickness: "Ultra-thin",
    crepeStructure: "Engineered",
    flowRate: "Medium (Negotiator-compressed; measurement-revised from prior 'Very fast' classification)",
    flowConsistency: "Extremely stable",
    bypassInteraction: "Neutral",
    cloggingRisk: "Very low",
    clarity: "Very high",
    body: "Low",
    sweetnessExpression: "Clean",
    paperTechnology: "FAST",
    bestArchetype: "Stability flat",
    compatibleSystems: "Orea / Kalita / April",
    owned: true,
    location: "Home",
    primaryUseCase: "Hand-folded maximum clarity flat bed; behaviorally indistinguishable from FLAT 2 FAST factory-fold per Project #2 measurement",
    measuredDrawdownSec: 117,
    measurementDose: "15g",
    measurementBaseline: "Sibarist FLAT 2 B3 (Project #2 baseline; 127.5s median)",
    measurementDate: "2026-05-24",
    measurementProject: "flat-bottom-filter-drawdown",
    bedBehaviorUnderLoad: 'late-forming-crater',
    measurementNote: "Hand-folded by Chris (first attempt); fold scoring on paper aided execution. Paper size used in measurement: unknown — see Project #2 open data items. Cross-confirmed with FLAT 2 FAST factory-fold (both at 117s exact) — strong evidence hand-fold quality is a non-factor with paper scoring + Negotiator compression.",
  },
  {
    name: "FLAT B3",
    manufacturer: "Sibarist",
    sku: "FLAT-B3",
    link: "https://sibarist.coffee/en-es/products/flat",
    paperShape: "Flat",
    sizeStandard: "Kalita-155/185",
    fitsBrewers: ["Orea", "Kalita", "April"],
    sealFitType: "Tight (low bypass)",
    material: "Specialty fiber (B3)",
    thickness: "Medium",
    crepeStructure: "Engineered",
    flowRate: "Medium",
    flowConsistency: "Extremely stable",
    bypassInteraction: "Reduces",
    cloggingRisk: "Very low",
    clarity: "High",
    body: "Medium",
    sweetnessExpression: "Structured",
    paperTechnology: "B3",
    bestArchetype: "Stability flat (controlled)",
    compatibleSystems: "Orea / Kalita / April",
    // Ownership corrected 2026-05-24 (Research Project #2 Step 0): Chris owns
    // FLAT 2 B3 (pre-folded successor), not this hand-fold variant. See FLAT 2 B3
    // entry below.
  },
  {
    name: "FLAT 2 B3",
    manufacturer: "Sibarist",
    sku: "FLAT2-B3",
    link: "https://sibarist.coffee/en-es/products/flat-2",
    paperShape: "Flat",
    sizeStandard: "Kalita-155/185",
    fitsBrewers: ["Orea", "Kalita", "April"],
    sealFitType: "Tight (zero-bypass per Sibarist design intent)",
    material: "Specialty fiber (B3)",
    thickness: "Medium",
    crepeStructure: "Engineered (pre-folded v2)",
    flowRate: "Medium (Negotiator-compressed)",
    flowConsistency: "Extremely stable",
    bypassInteraction: "Reduces (Sibarist 'Zero-Bypass' design)",
    cloggingRisk: "Very low",
    clarity: "High",
    body: "Medium",
    sweetnessExpression: "Structured",
    paperTechnology: "B3 (pre-folded v2)",
    bestArchetype: "Stability flat (controlled)",
    compatibleSystems: "Orea / Kalita / April",
    owned: true,
    location: "Home",
    primaryUseCase: "Pre-folded structured flat extraction; Chris's active workhorse flat baseline",
    measuredDrawdownSec: 127.5,
    measurementDose: "15g",
    measurementBaseline: "Self (Research Project #2 baseline; 3-replicate median, 6s range across pulls)",
    measurementDate: "2026-05-24",
    measurementProject: "flat-bottom-filter-drawdown",
    bedBehaviorUnderLoad: 'late-forming-crater',
    measurementNote: "Tested in size S with Orea Negotiator (compressed config). Size M not yet tested; size confound vs FLAT 2 FAST (tested in M) queued as audit item #9. Sibarist markets FLAT 2 as 'Zero-Bypass' design — micro-folds friction is a known tradeoff, not a defect. Exploratory Sibarist Booster 45 pull: 52s drawdown (-75.5s vs no-Booster) — Booster effectively converts B3 to free-seating-cluster speed.",
  },
  {
    name: "FLAT 2 FAST",
    manufacturer: "Sibarist",
    sku: "FLAT2-FAST",
    link: "https://sibarist.coffee/en-es/products/flat-2",
    paperShape: "Flat",
    sizeStandard: "Kalita-155/185",
    fitsBrewers: ["Orea", "Kalita", "April"],
    sealFitType: "Tight (zero-bypass per Sibarist design intent)",
    material: "Specialty fiber (FAST)",
    thickness: "Ultra-thin",
    crepeStructure: "Engineered (pre-folded v2)",
    flowRate: "Medium (Negotiator-compressed; measurement-revised from inherited 'Very fast' classification)",
    flowConsistency: "Extremely stable",
    bypassInteraction: "Neutral (Sibarist 'Zero-Bypass' design)",
    cloggingRisk: "Very low",
    clarity: "Very high",
    body: "Low",
    sweetnessExpression: "Clean",
    paperTechnology: "FAST (pre-folded v2)",
    bestArchetype: "Stability flat",
    compatibleSystems: "Orea / Kalita / April",
    owned: true,
    location: "Home",
    primaryUseCase: "Pre-folded clarity-forward flat extraction; FAST fiber in v2 pre-folded format",
    measuredDrawdownSec: 117,
    measurementDose: "15g",
    measurementBaseline: "Sibarist FLAT 2 B3 (Project #2 baseline; 127.5s median, 6s range)",
    measurementDate: "2026-05-24",
    measurementProject: "flat-bottom-filter-drawdown",
    bedBehaviorUnderLoad: 'late-forming-crater',
    measurementNote: "Tested in size M with Orea Negotiator (sits proud of brewer rim — see audit item #9 on size confound vs FLAT 2 B3 size S baseline); size S not yet tested. Cross-confirmed with FLAT FAST hand-fold (both at 117s exact). Exploratory Sibarist Booster 45 pull: 105s drawdown (-12s vs no-Booster) — much less Booster sensitivity than FLAT 2 B3 (which dropped -75.5s with Booster). Effect is fiber-specific OR size-specific (confounded).",
  },
  {
    name: "WAVE B3",
    manufacturer: "Sibarist",
    sku: "WAVE-B3",
    link: "https://sibarist.coffee/en-es/products/wave",
    paperShape: "Wave",
    sizeStandard: "Kalita-155/185",
    fitsBrewers: ["Orea", "Kalita", "Stagg"],
    sealFitType: "Tight (structured fit)",
    material: "Specialty fiber (B3)",
    thickness: "Medium",
    crepeStructure: "Engineered",
    flowRate: "Medium (Negotiator-compressed) / Fast (free-seating in Orea) — context-dependent",
    flowConsistency: "Extremely stable",
    bypassInteraction: "Reduces",
    cloggingRisk: "Very low",
    clarity: "High",
    body: "Medium",
    sweetnessExpression: "Structured",
    paperTechnology: "B3",
    bestArchetype: "Stability flat (controlled)",
    compatibleSystems: "Orea / Kalita",
    owned: true,
    location: "Home",
    primaryUseCase: "Controlled flat extraction; functionally a flat-bottom paper in Orea (cupcake walls free-seat without Negotiator)",
    measuredDrawdownSec: 48.5,
    measurementDose: "15g",
    measurementBaseline: "Sibarist FLAT 2 B3 (Project #2 baseline; 127.5s median)",
    measurementDate: "2026-05-24",
    measurementProject: "flat-bottom-filter-drawdown",
    bedBehaviorUnderLoad: 'late-forming-crater',
    measurementNote: "Free-seating in Orea v4 (no Negotiator); zero bypass observed. Same drawdown cluster as xBloom (48.5s vs xBloom's 50s) — geometry/compression dominates fiber. paperShape:'Wave' is misleading — functionally a flat-bottom paper with cupcake-walled geometry; see Project #2 audit item #2. flowRate is context-dependent: ~48s free-seating vs ~120-130s if Negotiator-compressed (not measured here but inferred from FLAT 2 B3 baseline behavior).",
  },
  {
    name: "UFO FAST",
    manufacturer: "Sibarist",
    sku: "UFO-FAST",
    link: "https://sibarist.coffee/en-es/products/ufo",
    paperShape: "Conical",
    sizeStandard: "Custom 80°",
    fitsBrewers: ["UFO dripper"],
    sealFitType: "Perfect fit (custom)",
    material: "Specialty fiber (FAST)",
    thickness: "Ultra-thin",
    crepeStructure: "Engineered",
    flowRate: "Very fast",
    flowConsistency: "Extremely stable",
    bypassInteraction: "Neutral",
    cloggingRisk: "Very low",
    clarity: "Very high",
    body: "Low",
    sweetnessExpression: "Clean",
    paperTechnology: "FAST",
    bestArchetype: "Clarity cone",
    compatibleSystems: "UFO",
    owned: true,
    location: "Home",
    primaryUseCase: "Extreme clarity expression (max bypass cone behavior)",
  },
  {
    name: "Sibarist HALO CONE FAST",
    manufacturer: "Sibarist",
    sku: "HALO-FAST",
    link: "https://sibarist.coffee/en-es/products/cone-bs",
    paperShape: "Conical (system-specific)",
    sizeStandard: "BS cone",
    fitsBrewers: ["Sibarist Brewing System (cone module)"],
    sealFitType: "Perfect seal (system-integrated)",
    material: "Specialty fiber (FAST)",
    thickness: "Ultra-thin",
    crepeStructure: "Engineered low resistance",
    flowRate: "Very fast",
    flowConsistency: "Extremely stable",
    bypassInteraction: "None (system sealed)",
    cloggingRisk: "Very low",
    clarity: "Very high",
    body: "Low",
    sweetnessExpression: "Clean",
    paperTechnology: "FAST",
    bestArchetype: "Clarity cone (system-level)",
    compatibleSystems: "Sibarist Brewing System",
    owned: true,
    location: "Home",
    primaryUseCase: "System-level peak clarity (eliminate fit + bypass variability)",
    measuredDrawdownSec: 108,
    measurementDose: "15g",
    measurementBaseline: "Sibarist HALO CONE B3 (Project #3b baseline; 134s median, 4s range — tightest in entire 3-project arc)",
    measurementDate: "2026-05-25",
    measurementProject: "specialty-cone-filter-drawdown",
    bedBehaviorUnderLoad: 'stable',
    measurementNote: "Sibarist Brewing System (system-integrated; no Negotiator/Booster needed). -26s vs HALO-B3 baseline = REAL (clears 4s noise floor), Moderately faster band (Step 3 grind comp: 0.3 finer). Cleanest single-paper classification of the entire 3-project arc. Same FAST fiber family as Project #1 CONE FAST + Project #2 FLAT 2 FAST — within-fiber-family consistency holds when paper-brewer-fit is eliminated by BS architecture (Lesson #35 brewer-as-paper-housing). | **RP4 (2026-05-26): NOT RE-MEASURED** — RP4 focused on V60-cohort papers in BS, not HALO family re-test. HALO-B3 baseline DRIFT in RP4 (91s vs P3 134s, RP4 AI-1 unresolved) raises question of whether HALO-FAST's P3 absolute (108s) would replicate; relative Δ vs baseline within P3's session is internally consistent (108-134 = -26 REAL faster classification holds within P3 context).",
  },
  {
    name: "Sibarist HALO CONE B3",
    manufacturer: "Sibarist",
    sku: "HALO-B3",
    link: "https://sibarist.coffee/en-es/products/cone-bs",
    paperShape: "Conical (system-specific)",
    sizeStandard: "BS cone",
    fitsBrewers: ["Sibarist Brewing System (cone module)"],
    sealFitType: "Perfect seal (system-integrated)",
    material: "Specialty fiber (B3)",
    thickness: "Medium",
    crepeStructure: "Engineered high structure",
    flowRate: "Medium",
    flowConsistency: "Extremely stable",
    bypassInteraction: "None (system sealed)",
    cloggingRisk: "Very low",
    clarity: "High",
    body: "Medium",
    sweetnessExpression: "Structured",
    paperTechnology: "B3",
    bestArchetype: "Clarity cone (controlled system)",
    compatibleSystems: "Sibarist Brewing System",
    owned: true,
    location: "Home",
    primaryUseCase: "System-level structured clarity (max repeatability cone system)",
    measuredDrawdownSec: 134,
    measurementDose: "15g",
    measurementBaseline: "Self (Research Project #3b baseline; 3-replicate median 134s, 4s range across pulls — tightest in entire 3-project arc vs Project #1's 8s, Project #2's 6s, Project #3a's 36s bimodal)",
    measurementDate: "2026-05-25",
    measurementProject: "specialty-cone-filter-drawdown",
    bedBehaviorUnderLoad: 'stable',
    measurementNote: "Sibarist Brewing System (system-integrated; no Negotiator needed, no brewer walls to seal against — Lesson #35 'brewer-as-paper-housing' architectural class). 4s baseline range is the tightest of any project in the arc. No-bed paper-only test (post-Pull-B5, Part Ba/Bb decomposition) showed NO self-choke whatsoever, refuting #3a's self-choke-as-paper-fiber-intrinsic hypothesis — refined as paper-brewer-INTERACTION artifact (Lesson #36, deepest insight of the entire 3-project arc). First-use brewer signal: clean baseline on Chris's never-opened-box brewer (Lesson #38). | **RP4 BS RE-MEASUREMENT (2026-05-26): 91s baseline** (median 90/91/94, range 4s — matches #3b 4s noise floor precedent exactly). **43s ABSOLUTE GAP from #3b's 134s measurement** with identical protocol (15g/250g, EG-1 6.5, Sudan Rume Natural blend continuity, BS). Candidate causes (RP4 AI-1, unresolved): paper batch drift / coffee blend-mix proportion / ambient state / operator technique drift between sessions. Both measurements internally consistent within session noise floors; cross-session absolute reproducibility appears non-trivial. Compile-session decision: keep #3b 134s as primary `measuredDrawdownSec` (P3 archive); relative classifications (HALO-FAST -26 REAL faster) remain valid within P3 context. **Lesson #36 PARTIALLY VALIDATED + REFINED per RP4-N4 — family-conditional, not universal.** Hario/Sibarist families validate Lesson #36; CAFEC family contradicts it (paper-fiber signal dominates).",
  },
  {
    name: "CONE 28 B3",
    manufacturer: "Sibarist",
    sku: "CONE28-B3",
    link: "https://sibarist.coffee/en-es/products/cone-28-30%C2%BA",
    paperShape: "Conical",
    sizeStandard: "Low-angle cone",
    fitsBrewers: ["Deep cone brewers"],
    sealFitType: "Tight",
    material: "Specialty fiber (B3)",
    thickness: "Medium",
    crepeStructure: "Engineered",
    flowRate: "Medium",
    flowConsistency: "Extremely stable",
    bypassInteraction: "Reduces",
    cloggingRisk: "Very low",
    clarity: "High",
    body: "Medium",
    sweetnessExpression: "Structured",
    paperTechnology: "B3",
    bestArchetype: "Clarity cone (controlled)",
    compatibleSystems: "Low-angle brewers, Funnex",
  },
  {
    name: "WAVE FAST",
    manufacturer: "Sibarist",
    sku: "WAVE-FAST",
    link: "https://sibarist.coffee/en-es/products/wave",
    paperShape: "Wave",
    sizeStandard: "Kalita-155/185",
    fitsBrewers: ["Orea", "Kalita", "Stagg"],
    sealFitType: "Tight (structured fit)",
    material: "Specialty fiber (FAST)",
    thickness: "Ultra-thin",
    crepeStructure: "Engineered",
    flowRate: "Very fast",
    flowConsistency: "Extremely stable",
    bypassInteraction: "Neutral",
    cloggingRisk: "Very low",
    clarity: "Very high",
    body: "Low",
    sweetnessExpression: "Clean",
    paperTechnology: "FAST",
    bestArchetype: "Stability flat",
    compatibleSystems: "Orea / Kalita",
  },
  {
    name: "FAST Trapezoid",
    manufacturer: "Sibarist",
    sku: "TRAP-FAST",
    link: "https://sibarist.coffee/en-es/products/fast-trapezoid",
    paperShape: "Trapezoid",
    sizeStandard: "102",
    fitsBrewers: ["Clever", "Melitta"],
    sealFitType: "Tight",
    material: "Specialty fiber (FAST)",
    thickness: "Ultra-thin",
    crepeStructure: "Engineered",
    flowRate: "Very fast",
    flowConsistency: "Extremely stable",
    bypassInteraction: "Neutral",
    cloggingRisk: "Very low",
    clarity: "Very high",
    body: "Low",
    sweetnessExpression: "Clean",
    paperTechnology: "FAST",
    bestArchetype: "Stability flat",
    compatibleSystems: "Clever / Melitta",
  },
  {
    name: "HYBRID FAST",
    manufacturer: "Sibarist",
    sku: "HYB-FAST",
    link: "https://sibarist.coffee/en-es/products/hybrid",
    paperShape: "Hybrid",
    sizeStandard: "Multi",
    fitsBrewers: ["Orea", "hybrid systems"],
    sealFitType: "Tight",
    material: "Specialty fiber (FAST)",
    thickness: "Ultra-thin",
    crepeStructure: "Engineered",
    flowRate: "Very fast",
    flowConsistency: "Extremely stable",
    bypassInteraction: "Neutral",
    cloggingRisk: "Very low",
    clarity: "Very high",
    body: "Low",
    sweetnessExpression: "Clean",
    paperTechnology: "FAST",
    bestArchetype: "Hybrid system",
    compatibleSystems: "Orea / hybrid brewers",
  },
  {
    name: "CONE BS FAST",
    manufacturer: "Sibarist",
    sku: "CONE-BS-FAST",
    link: "https://sibarist.coffee/en-es/products/cone-bs",
    paperShape: "Conical",
    sizeStandard: "V60-02",
    fitsBrewers: ["V60", "Origami"],
    sealFitType: "Tight",
    material: "Specialty fiber (FAST)",
    thickness: "Ultra-thin",
    crepeStructure: "Engineered",
    flowRate: "Very fast",
    flowConsistency: "Extremely stable",
    bypassInteraction: "Neutral",
    cloggingRisk: "Very low",
    clarity: "Very high",
    body: "Low",
    sweetnessExpression: "Clean",
    paperTechnology: "FAST",
    bestArchetype: "Clarity cone",
    compatibleSystems: "V60 / Origami",
  },
  {
    name: "CONE BS B3",
    manufacturer: "Sibarist",
    sku: "CONE-BS-B3",
    link: "https://sibarist.coffee/en-es/products/cone-bs",
    paperShape: "Conical",
    sizeStandard: "V60-02",
    fitsBrewers: ["V60", "Origami"],
    sealFitType: "Tight",
    material: "Specialty fiber (B3)",
    thickness: "Medium",
    crepeStructure: "Engineered",
    flowRate: "Medium",
    flowConsistency: "Extremely stable",
    bypassInteraction: "Reduces",
    cloggingRisk: "Very low",
    clarity: "High",
    body: "Medium",
    sweetnessExpression: "Structured",
    paperTechnology: "B3",
    bestArchetype: "Clarity cone (controlled)",
    compatibleSystems: "V60 / Origami",
  },
  {
    name: "Orea Z1 FAST",
    manufacturer: "Sibarist",
    sku: "Z1-FAST",
    link: "https://sibarist.coffee/en-es/products/orea-z1",
    paperShape: "Round",
    sizeStandard: "70mm",
    fitsBrewers: ["Orea Z1 (zero-bypass)"],
    sealFitType: "Perfect seal (zero bypass)",
    material: "Specialty fiber (FAST)",
    thickness: "Ultra-thin",
    crepeStructure: "Engineered",
    flowRate: "Very fast",
    flowConsistency: "Extremely stable",
    bypassInteraction: "None",
    cloggingRisk: "Very low",
    clarity: "Very high",
    body: "Low",
    sweetnessExpression: "Clean",
    paperTechnology: "FAST",
    bestArchetype: "Zero-bypass push",
    compatibleSystems: "Orea Z1",
  },
  {
    name: "Orea Z1 B3",
    manufacturer: "Sibarist",
    sku: "Z1-B3",
    link: "https://sibarist.coffee/en-es/products/orea-z1",
    paperShape: "Round",
    sizeStandard: "70mm",
    fitsBrewers: ["Orea Z1 (zero-bypass)"],
    sealFitType: "Perfect seal (zero bypass)",
    material: "Specialty fiber (B3)",
    thickness: "Medium",
    crepeStructure: "Engineered",
    flowRate: "Medium",
    flowConsistency: "Extremely stable",
    bypassInteraction: "None",
    cloggingRisk: "Very low",
    clarity: "High",
    body: "Medium",
    sweetnessExpression: "Structured",
    paperTechnology: "B3",
    bestArchetype: "Zero-bypass push (controlled)",
    compatibleSystems: "Orea Z1",
  },
  {
    name: "Orea FAST",
    manufacturer: "Sibarist",
    sku: "OREA-FAST",
    link: "https://sibarist.coffee/en-es/products/orea",
    paperShape: "Flat",
    sizeStandard: "Kalita-185",
    fitsBrewers: ["Orea V3", "V4"],
    sealFitType: "Tight (low bypass)",
    material: "Specialty fiber (FAST)",
    thickness: "Ultra-thin",
    crepeStructure: "Engineered",
    flowRate: "Very fast",
    flowConsistency: "Extremely stable",
    bypassInteraction: "Neutral",
    cloggingRisk: "Very low",
    clarity: "Very high",
    body: "Low",
    sweetnessExpression: "Clean",
    paperTechnology: "FAST",
    bestArchetype: "Stability flat",
    compatibleSystems: "Orea",
  },
  {
    name: "Orea B3",
    manufacturer: "Sibarist",
    sku: "OREA-B3",
    link: "https://sibarist.coffee/en-es/products/orea",
    paperShape: "Flat",
    sizeStandard: "Kalita-185",
    fitsBrewers: ["Orea V3", "V4"],
    sealFitType: "Tight (low bypass)",
    material: "Specialty fiber (B3)",
    thickness: "Medium",
    crepeStructure: "Engineered",
    flowRate: "Medium",
    flowConsistency: "Extremely stable",
    bypassInteraction: "Reduces",
    cloggingRisk: "Very low",
    clarity: "High",
    body: "Medium",
    sweetnessExpression: "Structured",
    paperTechnology: "B3",
    bestArchetype: "Stability flat (controlled)",
    compatibleSystems: "Orea",
  },
  {
    name: "Orea O1 FAST",
    manufacturer: "Sibarist",
    sku: "O1-FAST",
    link: "https://sibarist.coffee/en-es/products/orea-o1",
    paperShape: "Flat",
    sizeStandard: "Kalita-155",
    fitsBrewers: ["Orea V1", "small brewers"],
    sealFitType: "Tight (low bypass)",
    material: "Specialty fiber (FAST)",
    thickness: "Ultra-thin",
    crepeStructure: "Engineered",
    flowRate: "Very fast",
    flowConsistency: "Extremely stable",
    bypassInteraction: "Neutral",
    cloggingRisk: "Very low",
    clarity: "Very high",
    body: "Low",
    sweetnessExpression: "Clean",
    paperTechnology: "FAST",
    bestArchetype: "Stability flat",
    compatibleSystems: "Orea (small format)",
  },
  {
    name: "Orea O1 B3",
    manufacturer: "Sibarist",
    sku: "O1-B3",
    link: "https://sibarist.coffee/en-es/products/orea-o1",
    paperShape: "Flat",
    sizeStandard: "Kalita-155",
    fitsBrewers: ["Orea V1", "small brewers"],
    sealFitType: "Tight (low bypass)",
    material: "Specialty fiber (B3)",
    thickness: "Medium",
    crepeStructure: "Engineered",
    flowRate: "Medium",
    flowConsistency: "Extremely stable",
    bypassInteraction: "Reduces",
    cloggingRisk: "Very low",
    clarity: "High",
    body: "Medium",
    sweetnessExpression: "Structured",
    paperTechnology: "B3",
    bestArchetype: "Stability flat (controlled)",
    compatibleSystems: "Orea (small format)",
  },
  {
    name: "Origami FAST",
    manufacturer: "Sibarist",
    sku: "ORIGAMI-FAST",
    link: "https://sibarist.coffee/en-es/products/origami",
    paperShape: "Hybrid",
    sizeStandard: "V60-02 / Wave 155",
    fitsBrewers: ["Origami (cone + wave)"],
    sealFitType: "Adaptive (tightens seal)",
    material: "Specialty fiber (FAST)",
    thickness: "Ultra-thin",
    crepeStructure: "Engineered",
    flowRate: "Very fast",
    flowConsistency: "Extremely stable",
    bypassInteraction: "Neutral",
    cloggingRisk: "Very low",
    clarity: "Very high",
    body: "Low",
    sweetnessExpression: "Clean",
    paperTechnology: "FAST",
    bestArchetype: "Hybrid (clarity + flat)",
    compatibleSystems: "Origami",
  },
  {
    name: "Origami B3",
    manufacturer: "Sibarist",
    sku: "ORIGAMI-B3",
    link: "https://sibarist.coffee/en-es/products/origami",
    paperShape: "Hybrid",
    sizeStandard: "V60-02 / Wave 155",
    fitsBrewers: ["Origami (cone + wave)"],
    sealFitType: "Adaptive (tightens seal)",
    material: "Specialty fiber (B3)",
    thickness: "Medium",
    crepeStructure: "Engineered",
    flowRate: "Medium",
    flowConsistency: "Extremely stable",
    bypassInteraction: "Reduces",
    cloggingRisk: "Very low",
    clarity: "High",
    body: "Medium",
    sweetnessExpression: "Structured",
    paperTechnology: "B3",
    bestArchetype: "Hybrid (controlled)",
    compatibleSystems: "Origami",
  },
  {
    // April×Sibarist FAST — one product, two vendor pages:
    // aprilcoffeeroasters.com/products/april-x-sibarist +
    // sibarist.coffee/products/april. Ultra-thin FAST-tech flat paper for the
    // April flatbed (standard + Hybrid): precise flow control, finer grinds /
    // higher doses without clogging. Owned 2026-06-01. (Merged with the former
    // duplicate "April x Sibarist Filter" entry, same SKU APRIL-FAST.)
    name: "April FAST",
    manufacturer: "Sibarist",
    sku: "APRIL-FAST",
    link: "https://sibarist.coffee/en-es/products/april",
    paperShape: "Flat",
    sizeStandard: "Kalita-155",
    fitsBrewers: ["April", "April Hybrid Brewer", "Orea"],
    sealFitType: "Tight (low bypass)",
    material: "Specialty fiber (FAST)",
    thickness: "Ultra-thin",
    crepeStructure: "Engineered",
    flowRate: "Very fast",
    flowConsistency: "Extremely stable",
    bypassInteraction: "Neutral",
    cloggingRisk: "Very low",
    clarity: "Very high",
    body: "Low",
    sweetnessExpression: "Clean",
    paperTechnology: "FAST",
    bestArchetype: "Stability flat",
    compatibleSystems: "April / Orea",
    owned: true,
    location: "Home",
    primaryUseCase: "High-clarity flat extraction (fine grind / high dose, controlled flow)",
  },
  {
    name: "April B3",
    manufacturer: "Sibarist",
    sku: "APRIL-B3",
    link: "https://sibarist.coffee/en-es/products/april",
    paperShape: "Flat",
    sizeStandard: "Kalita-155",
    fitsBrewers: ["April", "April Hybrid Brewer"],
    sealFitType: "Tight (low bypass)",
    material: "Specialty fiber (B3)",
    thickness: "Medium",
    crepeStructure: "Engineered",
    flowRate: "Medium",
    flowConsistency: "Extremely stable",
    bypassInteraction: "Reduces",
    cloggingRisk: "Very low",
    clarity: "High",
    body: "Medium",
    sweetnessExpression: "Structured",
    paperTechnology: "B3",
    bestArchetype: "Stability flat (controlled)",
    compatibleSystems: "April",
  },
  {
    name: "UFO B3",
    manufacturer: "Sibarist",
    sku: "UFO-B3",
    link: "https://sibarist.coffee/en-es/products/ufo",
    paperShape: "Conical",
    sizeStandard: "Custom 80°",
    fitsBrewers: ["UFO dripper"],
    sealFitType: "Perfect fit (custom)",
    material: "Specialty fiber (B3)",
    thickness: "Medium",
    crepeStructure: "Engineered",
    flowRate: "Medium",
    flowConsistency: "Extremely stable",
    bypassInteraction: "Reduces",
    cloggingRisk: "Very low",
    clarity: "High",
    body: "Medium",
    sweetnessExpression: "Structured",
    paperTechnology: "B3",
    bestArchetype: "Clarity cone (controlled)",
    compatibleSystems: "UFO",
  },
  {
    name: "Weber Bird FAST",
    manufacturer: "Sibarist",
    sku: "BIRD-FAST",
    link: "https://sibarist.coffee/en-es/products/weber-workshops-bird",
    paperShape: "Round",
    sizeStandard: "Custom",
    fitsBrewers: ["Weber Bird (vacuum)"],
    sealFitType: "Perfect seal (zero bypass)",
    material: "Specialty fiber (FAST)",
    thickness: "Ultra-thin",
    crepeStructure: "Engineered",
    flowRate: "Very fast",
    flowConsistency: "Extremely stable",
    bypassInteraction: "None",
    cloggingRisk: "Very low",
    clarity: "Very high",
    body: "Low",
    sweetnessExpression: "Clean",
    paperTechnology: "FAST",
    bestArchetype: "Zero-bypass push",
    compatibleSystems: "Weber Bird",
  },
  {
    name: "Weber Bird B3",
    manufacturer: "Sibarist",
    sku: "BIRD-B3",
    link: "https://sibarist.coffee/en-es/products/weber-workshops-bird",
    paperShape: "Round",
    sizeStandard: "Custom",
    fitsBrewers: ["Weber Bird (vacuum)"],
    sealFitType: "Perfect seal (zero bypass)",
    material: "Specialty fiber (B3)",
    thickness: "Medium",
    crepeStructure: "Engineered",
    flowRate: "Medium",
    flowConsistency: "Extremely stable",
    bypassInteraction: "None",
    cloggingRisk: "Very low",
    clarity: "High",
    body: "Medium",
    sweetnessExpression: "Structured",
    paperTechnology: "B3",
    bestArchetype: "Zero-bypass push (controlled)",
    compatibleSystems: "Weber Bird",
  },
  {
    name: "Weber Bird Paper Filters",
    manufacturer: "Weber Workshops",
    sku: "BIRD-FILTER",
    link: "https://weberworkshops.com/products/bird-paper-filters",
    paperShape: "Round (system-specific)",
    sizeStandard: "Bird standard",
    fitsBrewers: ["Weber Workshops Bird"],
    sealFitType: "Perfect seal (zero-bypass)",
    material: "Refined pulp",
    thickness: "Medium",
    crepeStructure: "Low",
    flowRate: "Medium-fast",
    flowConsistency: "Extremely stable",
    bypassInteraction: "None (zero bypass)",
    cloggingRisk: "Low",
    clarity: "High",
    body: "High",
    sweetnessExpression: "Structured-clean",
    paperTechnology: "Standard+",
    bestArchetype: "Zero-bypass push",
    compatibleSystems: "Weber Bird",
    owned: true,
    location: "Home",
    primaryUseCase: "Maximum extraction without bypass (pressure-driven saturation extraction)",
  },
  {
    name: "xBloom Premium Paper Filters",
    manufacturer: "xBloom",
    sku: "XBLOOM-STD",
    link: "https://xbloom.com/products/xbloom-premium-paper-filters",
    paperShape: "Flat",
    sizeStandard: "Kalita-155/185",
    fitsBrewers: ["xBloom", "Kalita", "Orea"],
    sealFitType: "Standard",
    material: "Refined pulp",
    thickness: "Thin",
    crepeStructure: "High",
    flowRate: "Fast",
    flowConsistency: "Very stable",
    bypassInteraction: "Neutral",
    cloggingRisk: "Low",
    clarity: "High",
    body: "Low",
    sweetnessExpression: "Clean",
    paperTechnology: "Standard+",
    bestArchetype: "Stability flat",
    compatibleSystems: "xBloom / Kalita / Orea",
    owned: true,
    location: "Home, Office",
    primaryUseCase: "Automated stability baseline (fast, consistent flat extraction)",
    measuredDrawdownSec: 50,
    measurementDose: "15g",
    measurementBaseline: "Sibarist FLAT 2 B3 (Project #2 baseline; 127.5s median)",
    measurementDate: "2026-05-24",
    measurementProject: "flat-bottom-filter-drawdown",
    bedBehaviorUnderLoad: 'late-forming-crater',
    measurementNote: "Free-seating in Orea v4 (no Negotiator); cupcake walls free-seat cleanly; zero bypass observed. Same drawdown cluster as WAVE B3 (50s vs WAVE B3's 48.5s) — geometry dominates fiber. WAVE B3 fits Orea slightly cleaner than xBloom Premium.",
  },
]

export const FILTER_NAMES: readonly string[] = FILTERS.map((f) => f.name)

export const FILTER_ALIASES: Record<string, string> = {
  "Espro Bloom": "xBloom Premium Paper Filters",
  "Espro Bloom (flat bottom)": "xBloom Premium Paper Filters",
  "Espro Bloom Flat": "xBloom Premium Paper Filters",
  "Espro Bloom - flat bottom": "xBloom Premium Paper Filters",
  "Espro Bloom flat-bottom filter": "xBloom Premium Paper Filters",
  "Espro Bloom (rinsed)": "xBloom Premium Paper Filters",
  "Sibarist UFO Fast Cone": "UFO FAST",
  "Filter: Sibarist UFO Fast Cone": "UFO FAST",
  "Sibarist B3 cone": "CONE B3",
  "Sibarist B3 flat, Size S": "FLAT B3",
  "Sibarist B3 Wave (size S)": "WAVE B3",
  "April brewer filter paper": "April Paper Filter",
  "April Brewer Paper": "April Paper Filter",
  "April Flat Bottom Paper": "April Paper Filter",
  "April paper filter": "April Paper Filter",
  "April x Sibarist Filter": "April FAST",
  "April x Sibarist": "April FAST",
  "April Fast Filter": "April FAST",
  "April Fast Filters": "April FAST",
  "Hario V60 paper": "Hario V60 Paper Filter 01 (Tabbed)",
  "Hario V60 Paper": "Hario V60 Paper Filter 01 (Tabbed)",
  "Hario V60 white paper": "Hario V60 Paper Filter 01 (Tabbed)",
  "CAFEC Abaca Plus": "CAFEC Abaca+ Cup 1 Cone Paper Filter",
  "Standard flat filter (no puck screen)": "xBloom Premium Paper Filters",
  "Sibarist FAST Flat": "FLAT FAST",
  "Sibarist FAST flat": "FLAT FAST",
  "Sibarist FAST - flat bottom": "FLAT FAST",
  "Sibarist FAST - flat, size S": "FLAT FAST",
  "Sibarist FAST Flat - Size S": "FLAT FAST",
  "Sibarist FAST - Flat (Size S)": "FLAT FAST",
  "Sibarist FAST - Flat S": "FLAT FAST",
  // FLAT 2 aliases (Project #2, 2026-05-24): re-pointed from FLAT FAST to
  // FLAT 2 FAST after Step 0 surfaced these were silently collapsing distinct
  // products. Historical brew rows may need diagnostic audit — see Project #2
  // audit item #7.
  "Sibarist FAST Flat 2 - Size S": "FLAT 2 FAST",
  "Sibarist FAST - Flat 2, Size S": "FLAT 2 FAST",
  "Sibarist FAST Flat 2 - Size M": "FLAT 2 FAST",
  "Sibarist B3 Flat 2 - Size S": "FLAT 2 B3",
  "Sibarist B3 - Flat 2, Size S": "FLAT 2 B3",
  "Sibarist B3 Flat 2 - Size M": "FLAT 2 B3",
  "Sibarist Flat 2 FAST": "FLAT 2 FAST",
  "Sibarist Flat 2 B3": "FLAT 2 B3",
  "Sibarist FAST - Flat, Size M": "FLAT FAST",
  "Sibarist FAST (flat bottom, imperfect fit)": "FLAT FAST",
  "Sibarist FAST (flat bottom)": "FLAT FAST",
  "Sibarist FAST": "FLAT FAST",
  "Sibarist FAST Cone": "CONE FAST",
}

export const FILTER_LOOKUP: CanonicalLookup = makeCanonicalLookup(
  FILTER_NAMES,
  FILTER_ALIASES,
)

// Back-compat exports.
export const isCanonicalFilter = FILTER_LOOKUP.isCanonical
export const findClosestFilter = FILTER_LOOKUP.findClosest

export function getFilterEntry(name: string | null | undefined): FilterEntry | null {
  if (!name) return null
  const canonical = FILTER_LOOKUP.canonicalize(name)
  if (!canonical) return null
  return FILTERS.find((f) => f.name === canonical) ?? null
}

export function getFilterDisplayName(name: string | null | undefined): string {
  if (!name) return ''
  const e = getFilterEntry(name)
  return e?.displayName ?? e?.name ?? name
}
