// Canonical registry of filter papers. Authored content lives in
// [docs/skills/brewing-equipment-expert/cluster/filters.md](../docs/skills/brewing-equipment-expert/cluster/filters.md);
// this file is the validation mirror generated from Chris's authored CSV
// (Registry - Taxonomy - Drippers and filter papers - Papers.csv, 69 rows
// pre-dedupe).
//
// Sprint 1f (2026-04-26): structural port + adoption. brews.filter is a
// text-only column (no FK to a filters table). Adding a new filter is a
// deliberate edit — add a `FilterEntry` to `FILTERS` and update the
// authored cluster doc.
//
// Wave 1 (2026-05-26, ADR-0011): authored doc migrated from
// docs/taxonomies/filters.md to the Brewing Equipment Expert sub-skill
// cluster. Old path is a redirect stub for back-compat.
//
// Paper sizes (S/M) and fold variants are intentionally NOT carried as
// separate canonical entries. Sibarist FLAT FAST Size S vs Size M are the
// same canonical paper for this taxonomy — strip the size suffix on
// canonicalize.
//
// "Espro Bloom" in legacy DB strings was a misnaming of the xBloom
// Premium Paper Filters (XBLOOM-STD), per Chris's plan-mode confirm.
// All 16 brews labeled "Espro Bloom*" alias to "xBloom Premium Paper
// Filters" — not a net-new canonical.
//
// Sibarist filter drift is brewer-aware. "Sibarist FAST" or "Sibarist
// FAST Cone" can mean FLAT FAST / CONE FAST / UFO FAST depending on the
// brewer paired with the brew. The migration handles ambiguous strings
// per-row with (brewer, filter) WHERE clauses; the runtime alias map
// only covers unambiguous variants (Sibarist UFO Fast Cone always means
// UFO FAST regardless of brewer; Sibarist FAST Flat always means FLAT
// FAST since "flat" is the shape descriptor).

import { makeCanonicalLookup, type CanonicalLookup } from './canonical-registry'

// ---------------------------------------------------------------------------
// Type shape
// ---------------------------------------------------------------------------

export interface FilterEntry {
  name: string
  displayName?: string
  manufacturer: string
  sku: string
  link?: string
  paperShape: string
  sizeStandard: string
  fitsBrewers: string[]
  sealFitType: string
  material: string
  thickness: string
  crepeStructure: string
  flowRate: string
  flowConsistency: string
  bypassInteraction: string
  cloggingRisk: string
  clarity: string
  body: string
  sweetnessExpression: string
  paperTechnology: string
  bestArchetype: string
  compatibleSystems: string
  owned?: boolean
  location?: string
  primaryUseCase?: string
  // Research Project #1 (cone-filter-drawdown, 2026-05-23) extension:
  // measured loaded-bed drawdown from controlled testing. Raw drawdown
  // stored at measurementDose; do not normalize across doses (drawdown-vs-dose
  // isn't linear). bedBehaviorUnderLoad is observation-time qualitative axis
  // parallel to flowRate. See docs/research-projects/{measurementProject}.md
  // for the protocol + raw data.
  measuredDrawdownSec?: number
  measurementDose?: string
  measurementBaseline?: string
  measurementDate?: string
  measurementProject?: string
  bedBehaviorUnderLoad?: 'stable' | 'late-forming-crater' | 'pour-impact-crater' | 'mixed'
  // measurementNote (Project #2, 2026-05-24): free-text context that the
  // structured fields can't capture — size variant tested, accessory used,
  // hand-fold provenance, size-confound flags, design-intent notes. Optional;
  // populate when the measurement number alone would mislead without context.
  measurementNote?: string
}

export const FILTERS: readonly FilterEntry[] = [
  // Project #2 (flat-bottom-filter-drawdown, 2026-05-24): measurement deferred —
  // oversized for Orea v4 (would have required forced compression), AND no peer
  // paper in Orea brewer to compare against (cohort-of-one). Re-measurement
  // candidate when (a) second April-fit paper enters inventory, OR (b) Project #3
  // native-brewer protocol covers it via the April brewer. See:
  // docs/research-projects/flat-bottom-filter-drawdown.md § Notes
  {
    name: "April Paper Filter",
    manufacturer: "April",
    sku: "APRIL-STD",
    link: "https://www.aprilcoffeeroasters.com/collections/april-brewing-accessories/products/april-paper-filter",
    paperShape: "Flat",
    sizeStandard: "Kalita-155",
    fitsBrewers: ["April", "Orea", "Kalita"],
    sealFitType: "Standard",
    material: "Wood pulp",
    thickness: "Medium",
    crepeStructure: "Medium",
    flowRate: "Medium",
    flowConsistency: "Stable",
    bypassInteraction: "Neutral",
    cloggingRisk: "Medium",
    clarity: "Medium",
    body: "Medium",
    sweetnessExpression: "Rounded",
    paperTechnology: "Standard",
    bestArchetype: "Stability flat",
    compatibleSystems: "April / Orea / Kalita",
    owned: true,
    location: "Home",
    primaryUseCase: "Balanced flat extraction (moderate flow, neutral profile)",
  },
  {
    name: "April x Sibarist Filter",
    manufacturer: "April",
    sku: "APRIL-FAST",
    link: "https://www.aprilcoffeeroasters.com/collections/april-brewing-accessories/products/april-x-sibarist",
    paperShape: "Flat",
    sizeStandard: "Kalita-155",
    fitsBrewers: ["April", "Orea"],
    sealFitType: "Tight (low bypass)",
    material: "Specialty fiber (FAST)",
    thickness: "Ultra-thin",
    crepeStructure: "Engineered",
    flowRate: "Very fast",
    flowConsistency: "Extremely stable",
    bypassInteraction: "Neutral",
    cloggingRisk: "Very low",
    clarity: "Very high",
    body: "Low",
    sweetnessExpression: "Clean",
    paperTechnology: "FAST",
    bestArchetype: "Stability flat",
    compatibleSystems: "April / Orea",
  },
  {
    name: "CAFEC T-92 - Cup 4 Light Roast Paper Filter",
    manufacturer: "Cafec",
    sku: "LC4-100W",
    link: "https://cafecusa.com/collections/filter-papers/products/cafec-pour-over",
    paperShape: "Conical",
    sizeStandard: "V60-02",
    fitsBrewers: ["V60", "Origami", "Cafec"],
    sealFitType: "Standard",
    material: "Wood pulp",
    thickness: "Thin",
    crepeStructure: "High",
    flowRate: "Fast",
    flowConsistency: "Stable",
    bypassInteraction: "Promotes",
    cloggingRisk: "Low",
    clarity: "High",
    body: "Low",
    sweetnessExpression: "Clean",
    paperTechnology: "Roast-specific",
    bestArchetype: "Clarity cone",
    compatibleSystems: "V60 / Origami",
    owned: true,
    location: "Home",
    primaryUseCase: "Peak clarity (max separationm, high-acid coffees)",
    measuredDrawdownSec: 80,
    measurementDose: "15g",
    measurementBaseline: "Sibarist CONE B3 = 60s @ 15g / EG-1 6.5 / Hario V60 Glass V60-01",
    measurementDate: "2026-05-23",
    measurementProject: "cone-filter-drawdown",
    bedBehaviorUnderLoad: 'late-forming-crater',
  },
  {
    name: "CAFEC T-90 - Cup 1 Medium Roast Paper Filter",
    manufacturer: "Cafec",
    sku: "MC1-100W",
    link: "https://cafecusa.com/collections/filter-papers/products/cafec-cup-1-pour-over-coffee-paper-filter-by-roasting-type-flow-rate-differences-for-specialty-coffee-medium-roast-faster-flow-rate-1-cup-size-v60-01",
    paperShape: "Conical",
    sizeStandard: "V60-01",
    fitsBrewers: ["V60", "Origami", "Cafec"],
    sealFitType: "Standard",
    material: "Wood pulp",
    thickness: "Medium",
    crepeStructure: "Medium",
    flowRate: "Medium-fast",
    flowConsistency: "Stable",
    bypassInteraction: "Neutral",
    cloggingRisk: "Medium",
    clarity: "Medium",
    body: "Medium",
    sweetnessExpression: "Rounded",
    paperTechnology: "Roast-specific",
    bestArchetype: "Stability flat (cone variant)",
    compatibleSystems: "V60 / Origami",
    owned: true,
    location: "Home",
    primaryUseCase: "Balanced cone extraction (softens acidity, rounds profile)",
  },
  {
    name: "CAFEC T-83 - Cup 1 Dark Roast Paper Filter",
    manufacturer: "Cafec",
    sku: "DC1-40W",
    link: "https://cafecusa.com/collections/filter-papers/products/cup-1-dark-roast-paper-filter-dc1-40w",
    paperShape: "Conical",
    sizeStandard: "V60-01",
    fitsBrewers: ["V60", "Origami", "Cafec"],
    sealFitType: "Standard",
    material: "Wood pulp",
    thickness: "Thick",
    crepeStructure: "Low",
    flowRate: "Slow",
    flowConsistency: "Stable",
    bypassInteraction: "Reduces",
    cloggingRisk: "High",
    clarity: "Low",
    body: "High",
    sweetnessExpression: "Muted",
    paperTechnology: "Roast-specific",
    bestArchetype: "Immersion hybrid (cone assist)",
    compatibleSystems: "V60 / Switch",
    owned: true,
    location: "Home",
    primaryUseCase: "Extraction push via resistance (increase contact time without grind change)",
  },
  {
    name: "CAFEC Abaca+ Cup 1 Cone Paper Filter",
    manufacturer: "Cafec",
    sku: "APC1-100W",
    link: "https://cafecusa.com/collections/filter-papers/products/copy-of-cafec-abaca-cup-1-cone-paper-filter-v60-01-ac1-100w",
    paperShape: "Conical",
    sizeStandard: "V60-01",
    fitsBrewers: ["V60", "Origami", "Cafec"],
    sealFitType: "Standard",
    material: "Abaca + pulp",
    thickness: "Thin",
    crepeStructure: "Medium",
    flowRate: "Fast",
    flowConsistency: "Stable",
    bypassInteraction: "Neutral",
    cloggingRisk: "Low",
    clarity: "High",
    body: "Low",
    sweetnessExpression: "Clean",
    paperTechnology: "Abaca",
    bestArchetype: "Clarity cone",
    compatibleSystems: "V60 / Origami",
  },
  {
    name: "CAFEC Abaca Cup 1 Cone Paper Filter",
    manufacturer: "Cafec",
    sku: "AC1-100W",
    link: "https://cafecusa.com/collections/filter-papers/products/cafec-abaca-coffee-paper-filter-for-specialty-coffee-1-cup",
    paperShape: "Conical",
    sizeStandard: "V60-01",
    fitsBrewers: ["V60", "Origami", "Cafec"],
    sealFitType: "Standard",
    material: "Abaca + pulp",
    thickness: "Thin",
    crepeStructure: "Medium",
    flowRate: "Fast",
    flowConsistency: "Stable",
    bypassInteraction: "Neutral",
    cloggingRisk: "Low",
    clarity: "High",
    body: "Low",
    sweetnessExpression: "Clean",
    paperTechnology: "Abaca",
    bestArchetype: "Clarity cone",
    compatibleSystems: "V60 / Origami",
  },
  {
    name: "CAFEC Abaca Cup 4 Cone Paper Filter (40 pack)",
    manufacturer: "Cafec",
    sku: "APC4-40W",
    link: "https://cafecusa.com/collections/filter-papers/products/copy-of-cafec-abaca-cup-4-cone-paper-filter-v60-02-apc4-40w",
    paperShape: "Conical",
    sizeStandard: "V60-02",
    fitsBrewers: ["V60", "Origami", "Cafec"],
    sealFitType: "Standard",
    material: "Abaca + pulp",
    thickness: "Thin",
    crepeStructure: "Medium",
    flowRate: "Fast",
    flowConsistency: "Stable",
    bypassInteraction: "Neutral",
    cloggingRisk: "Low",
    clarity: "High",
    body: "Low",
    sweetnessExpression: "Clean",
    paperTechnology: "Abaca",
    bestArchetype: "Clarity cone",
    compatibleSystems: "V60 / Origami",
    owned: true,
    location: "Home",
    primaryUseCase: "Fast clarity baseline (standard high-flow reference; owned in both 40-pack assortment and 100-pack standalone variants)",
    measuredDrawdownSec: 72,
    measurementDose: "15g",
    measurementBaseline: "Sibarist CONE B3 = 60s @ 15g / EG-1 6.5 / Hario V60 Glass V60-01",
    measurementDate: "2026-05-23",
    measurementProject: "cone-filter-drawdown",
    bedBehaviorUnderLoad: 'late-forming-crater',
  },
  {
    name: "CAFEC T-92 - Cup 1 Light Roast Paper Filter (slow)",
    manufacturer: "Cafec",
    sku: "LC1-100W",
    link: "https://cafecusa.com/collections/filter-papers/products/cafec-cup-1-pour-over-coffee-paper-filter-by-roasting-type-flow-rate-differences-for-specialty-coffee-light-roast-slower-flow-rate-1-cup-size-v60-01",
    paperShape: "Conical",
    sizeStandard: "V60-01",
    fitsBrewers: ["V60", "Origami", "Cafec"],
    sealFitType: "Standard",
    material: "Wood pulp",
    thickness: "Thin",
    crepeStructure: "High",
    flowRate: "Medium",
    flowConsistency: "Stable",
    bypassInteraction: "Promotes",
    cloggingRisk: "Low",
    clarity: "High",
    body: "Low",
    sweetnessExpression: "Clean",
    paperTechnology: "Roast-specific",
    bestArchetype: "Clarity cone",
    compatibleSystems: "V60 / Origami",
  },
  {
    name: "CAFEC Abaca+ Deep 27 Coffee Filter (white)",
    manufacturer: "Cafec",
    sku: "AFD27-100W",
    link: "https://cafecusa.com/products/copy-of-cafec-abaca-cup-4-cone-paper-filter-v60-02-ac4-100w-3",
    paperShape: "Conical (deep)",
    sizeStandard: "Deep27",
    fitsBrewers: ["Cafec Deep27", "Funnex"],
    sealFitType: "Tight (deep fit)",
    material: "Abaca+ (refined blend)",
    thickness: "Thin",
    crepeStructure: "Medium-high",
    flowRate: "Fast",
    flowConsistency: "Very stable",
    bypassInteraction: "Reduces (depth-driven)",
    cloggingRisk: "Low",
    clarity: "High",
    body: "Medium",
    sweetnessExpression: "Clean but weighted",
    paperTechnology: "Abaca",
    bestArchetype: "Clarity cone (deep extraction)",
    compatibleSystems: "Cafec Deep27 systems, Funnex",
    owned: true,
    location: "Home",
    primaryUseCase: "Deep extraction clarity (increase contact time via bed depth, not resistance)",
  },
  {
    name: "CAFEC Abaca Cup 4 Cone Paper Filter",
    manufacturer: "Cafec",
    sku: "AC4-100W",
    link: "https://cafecusa.com/collections/filter-papers/products/cafec-abaca-coffee-paper-filter-for-specialty-coffee",
    paperShape: "Conical",
    sizeStandard: "V60-02",
    fitsBrewers: ["V60", "Origami", "Cafec", "Orea Apex"],
    sealFitType: "Standard",
    material: "Abaca + pulp",
    thickness: "Thin",
    crepeStructure: "Medium",
    flowRate: "Fast",
    flowConsistency: "Stable",
    bypassInteraction: "Neutral",
    cloggingRisk: "Low",
    clarity: "High",
    body: "Low",
    sweetnessExpression: "Clean",
    paperTechnology: "Abaca",
    bestArchetype: "Clarity cone",
    compatibleSystems: "V60 / Origami / Orea Apex",
  },
  {
    name: "CAFEC Cup 4 Medium Roast Paper Filter",
    manufacturer: "Cafec",
    sku: "MC4-100W",
    link: "https://cafecusa.com/collections/filter-papers/products/copy-of-cafec-cup-4-medium-roast-paper-filter-v60-02-mc4-100w-2",
    paperShape: "Conical",
    sizeStandard: "V60-02",
    fitsBrewers: ["V60", "Origami", "Cafec"],
    sealFitType: "Standard",
    material: "Wood pulp",
    thickness: "Medium",
    crepeStructure: "Medium",
    flowRate: "Medium-fast",
    flowConsistency: "Stable",
    bypassInteraction: "Neutral",
    cloggingRisk: "Medium",
    clarity: "Medium",
    body: "Medium",
    sweetnessExpression: "Rounded",
    paperTechnology: "Roast-specific",
    bestArchetype: "Stability flat (cone variant)",
    compatibleSystems: "V60 / Origami",
    owned: true,
    location: "Home",
    primaryUseCase: "Owned via Cafec 4-pack assortment (40-pack variant); medium-roast specific",
    measuredDrawdownSec: 60,
    measurementDose: "15g",
    measurementBaseline: "Sibarist CONE B3 = 60s @ 15g / EG-1 6.5 / Hario V60 Glass V60-01",
    measurementDate: "2026-05-23",
    measurementProject: "cone-filter-drawdown",
    bedBehaviorUnderLoad: 'mixed',
  },
  {
    name: "CAFEC Cup 4 Dark Roast Paper Filter",
    manufacturer: "Cafec",
    sku: "DC4-100W",
    link: "https://cafecusa.com/collections/filter-papers/products/copy-of-cafec-cup-4-dark-roast-paper-filter-v60-02-dc4-100w",
    paperShape: "Conical",
    sizeStandard: "V60-02",
    fitsBrewers: ["V60", "Origami", "Cafec"],
    sealFitType: "Standard",
    material: "Wood pulp",
    thickness: "Thick",
    crepeStructure: "Low",
    flowRate: "Slow",
    flowConsistency: "Stable",
    bypassInteraction: "Reduces",
    cloggingRisk: "High",
    clarity: "Low",
    body: "High",
    sweetnessExpression: "Muted",
    paperTechnology: "Roast-specific",
    bestArchetype: "Immersion hybrid (cone assist)",
    compatibleSystems: "V60 / Switch / Clever",
    owned: true,
    location: "Home",
    primaryUseCase: "Owned via Cafec 4-pack assortment (40-pack variant); dark-roast specific. NOTE: measured drawdown (68s) contradicts registry flowRate 'Slow' + thickness 'Thick' cells. See cone-filter-drawdown.md for the Cafec roast-specific paper finding.",
    measuredDrawdownSec: 68,
    measurementDose: "15g",
    measurementBaseline: "Sibarist CONE B3 = 60s @ 15g / EG-1 6.5 / Hario V60 Glass V60-01",
    measurementDate: "2026-05-23",
    measurementProject: "cone-filter-drawdown",
    bedBehaviorUnderLoad: 'late-forming-crater',
  },
  {
    name: "CAFEC Abaca Trapezoid Filter 102",
    manufacturer: "Cafec",
    sku: "AB-102-100W",
    link: "https://cafecusa.com/collections/filter-papers/products/cafec-102-abaca-trapezoid-paper-filter-for-3-5-cups-100pcs-pack-disposable-pour-over-drip-coffee-paper-filter-made-of-eco-friendly-refined-virgin-pulp-for-better-tasting-brewing-pour-over-dripper-white",
    paperShape: "Trapezoid",
    sizeStandard: "102",
    fitsBrewers: ["Clever", "Melitta", "OXO", "Cafec Oval"],
    sealFitType: "Standard",
    material: "Abaca + pulp",
    thickness: "Thin",
    crepeStructure: "Medium",
    flowRate: "Fast",
    flowConsistency: "Stable",
    bypassInteraction: "Neutral",
    cloggingRisk: "Low",
    clarity: "High",
    body: "Low",
    sweetnessExpression: "Clean",
    paperTechnology: "Abaca",
    bestArchetype: "Stability flat",
    compatibleSystems: "Trapezoid systems",
  },
  {
    name: "CAFEC Abaca Trapezoid Filter 101",
    manufacturer: "Cafec",
    sku: "AB-101-100W",
    link: "https://cafecusa.com/collections/filter-papers/products/cafec-101-abaca-trapezoid-paper-filter-for-1-3-cups-100pcs-pack-disposable-pour-over-drip-coffee-paper-filter-made-of-eco-friendly-refined-virgin-pulp-for-better-tasting-brewing-pour-over-dripper-white",
    paperShape: "Trapezoid",
    sizeStandard: "101",
    fitsBrewers: ["Clever", "Melitta (small)", "Cafec Oval"],
    sealFitType: "Standard",
    material: "Abaca + pulp",
    thickness: "Thin",
    crepeStructure: "Medium",
    flowRate: "Fast",
    flowConsistency: "Stable",
    bypassInteraction: "Neutral",
    cloggingRisk: "Low",
    clarity: "High",
    body: "Low",
    sweetnessExpression: "Clean",
    paperTechnology: "Abaca",
    bestArchetype: "Stability flat",
    compatibleSystems: "Trapezoid systems",
  },
  {
    name: "CAFEC Abaca Trapezoid Filter 102 (Alt SKU)",
    manufacturer: "Cafec",
    sku: "AB-102-100W",
    link: "https://cafecusa.com/collections/filter-papers/products/copy-of-cafec-trapezoid-102-cup-3-5-abaca-trapezoid-paper-filter-ab-102-100w",
    paperShape: "Trapezoid",
    sizeStandard: "102",
    fitsBrewers: ["Clever", "Melitta", "OXO", "Cafec Oval"],
    sealFitType: "Standard",
    material: "Abaca + pulp",
    thickness: "Thin",
    crepeStructure: "Medium",
    flowRate: "Fast",
    flowConsistency: "Stable",
    bypassInteraction: "Neutral",
    cloggingRisk: "Low",
    clarity: "High",
    body: "Low",
    sweetnessExpression: "Clean",
    paperTechnology: "Abaca",
    bestArchetype: "Stability flat",
    compatibleSystems: "Trapezoid systems",
  },
  {
    name: "CAFEC SFP Cup 4 Cone Paper Filter",
    manufacturer: "Cafec",
    sku: "SFP4-100W",
    link: "https://cafecusa.com/collections/filter-papers/products/sfp-cup-4-cone-paper-filter-sfp4-100w",
    paperShape: "Conical",
    sizeStandard: "V60-02",
    fitsBrewers: ["V60", "Origami", "Cafec"],
    sealFitType: "Tight (low bypass)",
    material: "Refined pulp",
    thickness: "Medium",
    crepeStructure: "High",
    flowRate: "Medium",
    flowConsistency: "Very stable",
    bypassInteraction: "Reduces",
    cloggingRisk: "Low",
    clarity: "High",
    body: "Medium",
    sweetnessExpression: "Clean",
    paperTechnology: "Structured",
    bestArchetype: "Clarity cone (controlled)",
    compatibleSystems: "V60 / Origami",
  },
  {
    name: "CAFEC Traditional Cup 1 Filter",
    manufacturer: "Cafec",
    sku: "CC1-100W",
    link: "https://cafecusa.com/collections/filter-papers/products/cafec-cup-1-traditional-paper-filter-cc1-100w",
    paperShape: "Conical",
    sizeStandard: "V60-01",
    fitsBrewers: ["V60", "Origami", "Cafec"],
    sealFitType: "Loose",
    material: "Wood pulp",
    thickness: "Medium",
    crepeStructure: "Low",
    flowRate: "Medium",
    flowConsistency: "Variable",
    bypassInteraction: "Promotes",
    cloggingRisk: "Medium",
    clarity: "Medium",
    body: "Medium",
    sweetnessExpression: "Rounded",
    paperTechnology: "Standard",
    bestArchetype: "Clarity cone (classic)",
    compatibleSystems: "V60 / Origami",
  },
  {
    name: "CAFEC Arita Ware Paper Filter",
    manufacturer: "Cafec",
    sku: "DDF-100W",
    link: "https://cafecusa.com/collections/filter-papers/products/copy-of-cafec-arita-ware-paper-filter-ddf-100w",
    paperShape: "Conical",
    sizeStandard: "V60-02",
    fitsBrewers: ["V60", "Origami", "Cafec"],
    sealFitType: "Tight (low bypass)",
    material: "Refined pulp",
    thickness: "Medium",
    crepeStructure: "High",
    flowRate: "Medium",
    flowConsistency: "Very stable",
    bypassInteraction: "Reduces",
    cloggingRisk: "Low",
    clarity: "High",
    body: "Medium",
    sweetnessExpression: "Clean",
    paperTechnology: "Structured",
    bestArchetype: "Clarity cone (controlled)",
    compatibleSystems: "V60 / Origami",
  },
  {
    name: "CAFEC Abaca Cup 4 Cone Paper Filter (brown 40)",
    manufacturer: "Cafec",
    sku: "AC4-40B",
    link: "https://cafecusa.com/collections/filter-papers/products/abaca-cup-4-cone-paper-filter-ac4-40b",
    paperShape: "Conical",
    sizeStandard: "V60-02",
    fitsBrewers: ["V60", "Origami", "Cafec"],
    sealFitType: "Standard",
    material: "Abaca + pulp (unbleached)",
    thickness: "Thin",
    crepeStructure: "Medium",
    flowRate: "Fast",
    flowConsistency: "Stable",
    bypassInteraction: "Neutral",
    cloggingRisk: "Low",
    clarity: "High",
    body: "Low",
    sweetnessExpression: "Clean",
    paperTechnology: "Abaca",
    bestArchetype: "Clarity cone",
    compatibleSystems: "V60 / Origami",
  },
  {
    name: "CAFEC Abaca Cup 4 Cone Paper Filter (brown 100)",
    manufacturer: "Cafec",
    sku: "AC4-100B",
    link: "https://cafecusa.com/collections/filter-papers/products/abaca-cup-4-cone-paper-filter-ac4-100b",
    paperShape: "Conical",
    sizeStandard: "V60-02",
    fitsBrewers: ["V60", "Origami", "Cafec"],
    sealFitType: "Standard",
    material: "Abaca + pulp (unbleached)",
    thickness: "Thin",
    crepeStructure: "Medium",
    flowRate: "Fast",
    flowConsistency: "Stable",
    bypassInteraction: "Neutral",
    cloggingRisk: "Low",
    clarity: "High",
    body: "Low",
    sweetnessExpression: "Clean",
    paperTechnology: "Abaca",
    bestArchetype: "Clarity cone",
    compatibleSystems: "V60 / Origami",
  },
  {
    name: "CAFEC Wave Paper Filter 250",
    manufacturer: "Cafec",
    sku: "WF250-250W",
    link: "https://cafecusa.com/collections/filter-papers/products/cafec-wave-paper-filters-250-no-250-wave-filter-250-sheets-bag-4-bags-per-carton-wf250-250w",
    paperShape: "Wave",
    sizeStandard: "Kalita-185",
    fitsBrewers: ["Kalita", "Orea", "April", "Stagg"],
    sealFitType: "Standard",
    material: "Wood pulp",
    thickness: "Medium",
    crepeStructure: "Medium",
    flowRate: "Medium",
    flowConsistency: "Stable",
    bypassInteraction: "Neutral",
    cloggingRisk: "Medium",
    clarity: "Medium",
    body: "Medium",
    sweetnessExpression: "Rounded",
    paperTechnology: "Standard",
    bestArchetype: "Stability flat",
    compatibleSystems: "Kalita / Orea / April",
  },
  {
    name: "CAFEC Abaca Cup 4 Cone Paper Filter (variant)",
    manufacturer: "Cafec",
    sku: "AC4-100W",
    link: "https://cafecusa.com/collections/filter-papers/products/copy-of-cafec-abaca-cup-4-cone-paper-filter-v60-02-ac4-100w-3",
    paperShape: "Conical",
    sizeStandard: "V60-02",
    fitsBrewers: ["V60", "Origami", "Cafec"],
    sealFitType: "Standard",
    material: "Abaca + pulp",
    thickness: "Thin",
    crepeStructure: "Medium",
    flowRate: "Fast",
    flowConsistency: "Stable",
    bypassInteraction: "Neutral",
    cloggingRisk: "Low",
    clarity: "High",
    body: "Low",
    sweetnessExpression: "Clean",
    paperTechnology: "Abaca",
    bestArchetype: "Clarity cone",
    compatibleSystems: "V60 / Origami",
  },
  {
    name: "CAFEC TH-1 Light Roast Paper Filter",
    manufacturer: "Cafec",
    sku: "TH1-4-100",
    link: "https://cafecusa.com/collections/filter-papers/products/cafec-th-1-cup-4-light-roast-paper-filter-v60-02-th14-100-copy",
    paperShape: "Conical",
    sizeStandard: "V60-02",
    fitsBrewers: ["V60", "Origami", "Cafec"],
    sealFitType: "Tight (low bypass)",
    material: "Refined pulp",
    thickness: "Thin",
    crepeStructure: "High",
    flowRate: "Fast",
    flowConsistency: "Very stable",
    bypassInteraction: "Reduces",
    cloggingRisk: "Low",
    clarity: "High",
    body: "Low",
    sweetnessExpression: "Clean",
    paperTechnology: "Structured",
    bestArchetype: "Clarity cone (controlled)",
    compatibleSystems: "V60 / Origami",
  },
  {
    name: "CAFEC TH-3 Medium Roast Paper Filter",
    manufacturer: "Cafec",
    sku: "TH3-4-100",
    link: "https://cafecusa.com/collections/filter-papers/products/cafec-th-3-cup-4-medium-roast-paper-filter-v60-02-th34-100-copy",
    paperShape: "Conical",
    sizeStandard: "V60-02",
    fitsBrewers: ["V60", "Origami", "Cafec"],
    sealFitType: "Tight (low bypass)",
    material: "Refined pulp",
    thickness: "Medium",
    crepeStructure: "High",
    flowRate: "Medium-fast",
    flowConsistency: "Very stable",
    bypassInteraction: "Reduces",
    cloggingRisk: "Low",
    clarity: "Medium",
    body: "Medium",
    sweetnessExpression: "Rounded",
    paperTechnology: "Structured",
    bestArchetype: "Stability flat (cone variant)",
    compatibleSystems: "V60 / Origami",
  },
  {
    name: "CAFEC TH-2 Dark Roast Paper Filter",
    manufacturer: "Cafec",
    sku: "TH2-4-100",
    link: "https://cafecusa.com/collections/filter-papers/products/cafec-th-2-cup-4-dark-roast-paper-filter-v60-02-th24-100-copy",
    paperShape: "Conical",
    sizeStandard: "V60-02",
    fitsBrewers: ["V60", "Origami", "Cafec"],
    sealFitType: "Tight (low bypass)",
    material: "Refined pulp",
    thickness: "Thick",
    crepeStructure: "High",
    flowRate: "Slow",
    flowConsistency: "Very stable",
    bypassInteraction: "Reduces",
    cloggingRisk: "Low",
    clarity: "Low",
    body: "High",
    sweetnessExpression: "Muted",
    paperTechnology: "Structured",
    bestArchetype: "Immersion hybrid (cone assist)",
    compatibleSystems: "V60 / Switch / Clever",
  },
  {
    name: "CAFEC Abaca Trapezoid Filter 101 (variant)",
    manufacturer: "Cafec",
    sku: "AB-101-100W",
    link: "https://cafecusa.com/collections/filter-papers/products/cafec-trapezoid-101-abaca-trapezoid-paper-filter-for-1-2-cups-100pcs-pack-ab-101-100w-copy",
    paperShape: "Trapezoid",
    sizeStandard: "101",
    fitsBrewers: ["Clever", "Melitta (small)", "Cafec Oval"],
    sealFitType: "Standard",
    material: "Abaca + pulp",
    thickness: "Thin",
    crepeStructure: "Medium",
    flowRate: "Fast",
    flowConsistency: "Stable",
    bypassInteraction: "Neutral",
    cloggingRisk: "Low",
    clarity: "High",
    body: "Low",
    sweetnessExpression: "Clean",
    paperTechnology: "Abaca",
    bestArchetype: "Stability flat",
    compatibleSystems: "Trapezoid systems",
  },
  {
    name: "Chemex Bonded Filter (Half Moon White)",
    manufacturer: "Chemex",
    sku: "CHEMEX-HM-W",
    link: "https://chemexcoffeemaker.com/products/chemex-bonded-filters-unfolded-half-moon",
    paperShape: "Conical (folded)",
    sizeStandard: "Chemex",
    fitsBrewers: ["Funnex", "Chemex"],
    sealFitType: "Loose (thick seal via paper)",
    material: "Bonded pulp",
    thickness: "Very thick",
    crepeStructure: "Low",
    flowRate: "Slow",
    flowConsistency: "Very stable",
    bypassInteraction: "Strongly reduces",
    cloggingRisk: "High",
    clarity: "High",
    body: "Very high",
    sweetnessExpression: "Heavy",
    paperTechnology: "Standard",
    bestArchetype: "Clarity cone (low bypass)",
    compatibleSystems: "Chemex / Funnex",
    owned: true,
    location: "Home",
    primaryUseCase: "Use as immersion-like cone (max body + filtration, suppresses brightness)",
  },
  {
    name: "Chemex Bonded Filter (Half Moon Natural)",
    manufacturer: "Chemex",
    sku: "CHEMEX-HM-N",
    link: "https://chemexcoffeemaker.com/products/chemex-bonded-filters-unfolded-half-moon-natural",
    paperShape: "Conical (folded)",
    sizeStandard: "Chemex",
    fitsBrewers: ["Funnex", "Chemex"],
    sealFitType: "Loose (thick seal via paper)",
    material: "Bonded pulp (unbleached)",
    thickness: "Very thick",
    crepeStructure: "Low",
    flowRate: "Slow",
    flowConsistency: "Very stable",
    bypassInteraction: "Strongly reduces",
    cloggingRisk: "High",
    clarity: "High",
    body: "Very high",
    sweetnessExpression: "Heavy",
    paperTechnology: "Standard",
    bestArchetype: "Clarity cone (low bypass)",
    compatibleSystems: "Chemex / Funnex",
  },
  {
    name: "Hario V60 Paper Filter 01 (Tabbed)",
    manufacturer: "Hario",
    sku: "VCF-01-100W",
    link: "https://www.hario-usa.com/products/paper-filter-for-01-drippers",
    paperShape: "Conical",
    sizeStandard: "V60-01",
    fitsBrewers: ["V60", "Origami"],
    sealFitType: "Loose",
    material: "Wood pulp",
    thickness: "Medium",
    crepeStructure: "Low",
    flowRate: "Medium",
    flowConsistency: "Variable",
    bypassInteraction: "Promotes",
    cloggingRisk: "Medium",
    clarity: "Medium",
    body: "Medium",
    sweetnessExpression: "Rounded",
    paperTechnology: "Standard",
    bestArchetype: "Clarity cone (classic)",
    compatibleSystems: "V60 / Origami",
    owned: true,
    location: "Home",
    primaryUseCase: "Baseline cone reference (introduces variability intentionally)",
    measuredDrawdownSec: 65,
    measurementDose: "15g",
    measurementBaseline: "Sibarist CONE B3 = 60s @ 15g / EG-1 6.5 / Hario V60 Glass V60-01",
    measurementDate: "2026-05-23",
    measurementProject: "cone-filter-drawdown",
    bedBehaviorUnderLoad: 'pour-impact-crater',
  },
  {
    name: "Hario V60 Paper Filter 01 (Untabbed)",
    manufacturer: "Hario",
    sku: "VCF-01-100M",
    link: "https://www.hario-usa.com/products/copy-of-paper-filter-for-01-drippers",
    paperShape: "Conical",
    sizeStandard: "V60-01",
    fitsBrewers: ["V60", "Origami"],
    sealFitType: "Loose",
    material: "Wood pulp",
    thickness: "Medium",
    crepeStructure: "Low",
    flowRate: "Medium",
    flowConsistency: "Variable",
    bypassInteraction: "Promotes",
    cloggingRisk: "Medium",
    clarity: "Medium",
    body: "Medium",
    sweetnessExpression: "Rounded",
    paperTechnology: "Standard",
    bestArchetype: "Clarity cone (classic)",
    compatibleSystems: "V60 / Origami",
  },
  {
    name: "Hario V60 Meteor Filter 02",
    manufacturer: "Hario",
    sku: "METEOR-02",
    link: "https://www.hario-usa.com/products/v60-meteor-filters-02",
    paperShape: "Conical",
    sizeStandard: "V60-02",
    fitsBrewers: ["V60", "Origami"],
    sealFitType: "Standard (improved seal)",
    material: "Refined pulp",
    thickness: "Thin",
    crepeStructure: "High",
    flowRate: "Fast",
    flowConsistency: "More stable",
    bypassInteraction: "Reduces",
    cloggingRisk: "Low",
    clarity: "High",
    body: "Low",
    sweetnessExpression: "Clean",
    paperTechnology: "Standard+",
    bestArchetype: "Clarity cone",
    compatibleSystems: "V60 / Origami",
    owned: true,
    location: "Home",
    primaryUseCase: "Improved clarity baseline (faster, more stable than standard Hario)",
    measuredDrawdownSec: 65,
    measurementDose: "15g",
    measurementBaseline: "Sibarist CONE B3 = 60s @ 15g / EG-1 6.5 / Hario V60 Glass V60-01",
    measurementDate: "2026-05-23",
    measurementProject: "cone-filter-drawdown",
    bedBehaviorUnderLoad: 'late-forming-crater',
  },
  {
    name: "Hario V60 Paper Filter 03",
    manufacturer: "Hario",
    sku: "VCF-03-100W",
    link: "https://www.hario-usa.com/products/paper-filter-for-03-drippers",
    paperShape: "Conical",
    sizeStandard: "V60-03",
    fitsBrewers: ["V60 (large brews)"],
    sealFitType: "Loose",
    material: "Wood pulp",
    thickness: "Medium",
    crepeStructure: "Low",
    flowRate: "Medium",
    flowConsistency: "Variable",
    bypassInteraction: "Promotes",
    cloggingRisk: "Medium",
    clarity: "Medium",
    body: "Medium",
    sweetnessExpression: "Rounded",
    paperTechnology: "Standard",
    bestArchetype: "Clarity cone (classic)",
    compatibleSystems: "V60",
  },
  {
    name: "Hario Flow Paper Filters",
    manufacturer: "Hario",
    sku: "FLOW-50",
    link: "https://www.hario-usa.com/products/flow-paper-filters-50ct",
    paperShape: "Wave",
    sizeStandard: "Kalita-155",
    fitsBrewers: ["Hario Flow", "flat brewers"],
    sealFitType: "Tight (center-supported)",
    material: "Refined pulp",
    thickness: "Thin",
    crepeStructure: "Engineered",
    flowRate: "Fast",
    flowConsistency: "Very stable",
    bypassInteraction: "Reduces",
    cloggingRisk: "Low",
    clarity: "High",
    body: "Low",
    sweetnessExpression: "Clean",
    paperTechnology: "Standard+",
    bestArchetype: "Stability flat",
    compatibleSystems: "Hario Flow / Orea / Kalita",
  },
  {
    name: "Kalita Wave 155 Filter",
    manufacturer: "Kalita",
    sku: "KW155-100",
    link: "https://kalitausa.com/products/kalita-wave-155-filter-100ct",
    paperShape: "Wave",
    sizeStandard: "Kalita-155",
    fitsBrewers: ["Kalita", "Orea", "April"],
    sealFitType: "Standard",
    material: "Wood pulp",
    thickness: "Medium",
    crepeStructure: "Medium",
    flowRate: "Medium",
    flowConsistency: "Moderately stable",
    bypassInteraction: "Neutral",
    cloggingRisk: "Medium",
    clarity: "Medium",
    body: "Medium",
    sweetnessExpression: "Rounded",
    paperTechnology: "Standard",
    bestArchetype: "Stability flat",
    compatibleSystems: "Kalita / Orea / April",
  },
  {
    name: "CONE FAST",
    manufacturer: "Sibarist",
    sku: "CONE-FAST",
    link: "https://sibarist.coffee/en-es/products/cone",
    paperShape: "Conical",
    sizeStandard: "V60-02",
    fitsBrewers: ["V60", "Origami", "Orea Apex"],
    sealFitType: "Tight (precision fit)",
    material: "Specialty fiber (FAST)",
    thickness: "Ultra-thin",
    crepeStructure: "Engineered low resistance",
    flowRate: "Very fast",
    flowConsistency: "Extremely stable",
    bypassInteraction: "Neutral",
    cloggingRisk: "Very low",
    clarity: "Very high",
    body: "Low",
    sweetnessExpression: "Clean",
    paperTechnology: "FAST",
    bestArchetype: "Clarity cone",
    compatibleSystems: "V60 / Origami / Orea Apex",
    owned: true,
    location: "Home",
    primaryUseCase: "Maximum clarity ceiling (fastest stable cone extraction)",
    measuredDrawdownSec: 45,
    measurementDose: "15g",
    measurementBaseline: "Sibarist CONE B3 = 60s @ 15g / EG-1 6.5 / Hario V60 Glass V60-01",
    measurementDate: "2026-05-23",
    measurementProject: "cone-filter-drawdown",
    bedBehaviorUnderLoad: 'pour-impact-crater',
  },
  {
    name: "CONE B3",
    manufacturer: "Sibarist",
    sku: "CONE-B3",
    link: "https://sibarist.coffee/en-es/products/cone",
    paperShape: "Conical",
    sizeStandard: "V60-02",
    fitsBrewers: ["V60", "Origami", "Orea Apex"],
    sealFitType: "Tight (precision fit)",
    material: "Specialty fiber (B3)",
    thickness: "Medium",
    crepeStructure: "Engineered high structure",
    flowRate: "Medium",
    flowConsistency: "Extremely stable",
    bypassInteraction: "Reduces",
    cloggingRisk: "Very low",
    clarity: "High",
    body: "Medium",
    sweetnessExpression: "Structured",
    paperTechnology: "B3",
    bestArchetype: "Clarity cone (controlled)",
    compatibleSystems: "V60 / Origami",
    owned: true,
    location: "Home",
    primaryUseCase: "Structured clarity (adds body without sacrificing cleanliness)",
    measuredDrawdownSec: 60,
    measurementDose: "15g",
    measurementBaseline: "Self (Research Project #1 baseline; 3-replicate median, 8s range across pulls)",
    measurementDate: "2026-05-23",
    measurementProject: "cone-filter-drawdown",
    bedBehaviorUnderLoad: 'late-forming-crater',
  },
  {
    name: "CONE 28 FAST",
    manufacturer: "Sibarist",
    sku: "CONE28-FAST",
    link: "https://sibarist.coffee/en-es/products/cone-28-30%C2%BA",
    paperShape: "Conical",
    sizeStandard: "Low-angle cone",
    fitsBrewers: ["Deep cone brewers"],
    sealFitType: "Tight",
    material: "Specialty fiber (FAST)",
    thickness: "Ultra-thin",
    crepeStructure: "Engineered",
    flowRate: "Very fast",
    flowConsistency: "Extremely stable",
    bypassInteraction: "Neutral",
    cloggingRisk: "Very low",
    clarity: "Very high",
    body: "Low",
    sweetnessExpression: "Clean",
    paperTechnology: "FAST",
    bestArchetype: "Clarity cone",
    compatibleSystems: "Low-angle brewers, Funnex",
    owned: true,
    location: "Home",
    primaryUseCase: "Extreme extraction clarity (deep cone + high flow, high extraction yield)",
  },
  {
    name: "FLAT FAST",
    manufacturer: "Sibarist",
    sku: "FLAT-FAST",
    link: "https://sibarist.coffee/en-es/products/flat",
    paperShape: "Flat",
    sizeStandard: "Kalita-155/185",
    fitsBrewers: ["Orea", "Kalita", "April"],
    sealFitType: "Tight (low bypass)",
    material: "Specialty fiber (FAST)",
    thickness: "Ultra-thin",
    crepeStructure: "Engineered",
    flowRate: "Medium (Negotiator-compressed; measurement-revised from prior 'Very fast' classification)",
    flowConsistency: "Extremely stable",
    bypassInteraction: "Neutral",
    cloggingRisk: "Very low",
    clarity: "Very high",
    body: "Low",
    sweetnessExpression: "Clean",
    paperTechnology: "FAST",
    bestArchetype: "Stability flat",
    compatibleSystems: "Orea / Kalita / April",
    owned: true,
    location: "Home",
    primaryUseCase: "Hand-folded maximum clarity flat bed; behaviorally indistinguishable from FLAT 2 FAST factory-fold per Project #2 measurement",
    measuredDrawdownSec: 117,
    measurementDose: "15g",
    measurementBaseline: "Sibarist FLAT 2 B3 (Project #2 baseline; 127.5s median)",
    measurementDate: "2026-05-24",
    measurementProject: "flat-bottom-filter-drawdown",
    bedBehaviorUnderLoad: 'late-forming-crater',
    measurementNote: "Hand-folded by Chris (first attempt); fold scoring on paper aided execution. Paper size used in measurement: unknown — see Project #2 open data items. Cross-confirmed with FLAT 2 FAST factory-fold (both at 117s exact) — strong evidence hand-fold quality is a non-factor with paper scoring + Negotiator compression.",
  },
  {
    name: "FLAT B3",
    manufacturer: "Sibarist",
    sku: "FLAT-B3",
    link: "https://sibarist.coffee/en-es/products/flat",
    paperShape: "Flat",
    sizeStandard: "Kalita-155/185",
    fitsBrewers: ["Orea", "Kalita", "April"],
    sealFitType: "Tight (low bypass)",
    material: "Specialty fiber (B3)",
    thickness: "Medium",
    crepeStructure: "Engineered",
    flowRate: "Medium",
    flowConsistency: "Extremely stable",
    bypassInteraction: "Reduces",
    cloggingRisk: "Very low",
    clarity: "High",
    body: "Medium",
    sweetnessExpression: "Structured",
    paperTechnology: "B3",
    bestArchetype: "Stability flat (controlled)",
    compatibleSystems: "Orea / Kalita / April",
    // Ownership corrected 2026-05-24 (Research Project #2 Step 0): Chris owns
    // FLAT 2 B3 (pre-folded successor), not this hand-fold variant. See FLAT 2 B3
    // entry below.
  },
  {
    name: "FLAT 2 B3",
    manufacturer: "Sibarist",
    sku: "FLAT2-B3",
    link: "https://sibarist.coffee/en-es/products/flat-2",
    paperShape: "Flat",
    sizeStandard: "Kalita-155/185",
    fitsBrewers: ["Orea", "Kalita", "April"],
    sealFitType: "Tight (zero-bypass per Sibarist design intent)",
    material: "Specialty fiber (B3)",
    thickness: "Medium",
    crepeStructure: "Engineered (pre-folded v2)",
    flowRate: "Medium (Negotiator-compressed)",
    flowConsistency: "Extremely stable",
    bypassInteraction: "Reduces (Sibarist 'Zero-Bypass' design)",
    cloggingRisk: "Very low",
    clarity: "High",
    body: "Medium",
    sweetnessExpression: "Structured",
    paperTechnology: "B3 (pre-folded v2)",
    bestArchetype: "Stability flat (controlled)",
    compatibleSystems: "Orea / Kalita / April",
    owned: true,
    location: "Home",
    primaryUseCase: "Pre-folded structured flat extraction; Chris's active workhorse flat baseline",
    measuredDrawdownSec: 127.5,
    measurementDose: "15g",
    measurementBaseline: "Self (Research Project #2 baseline; 3-replicate median, 6s range across pulls)",
    measurementDate: "2026-05-24",
    measurementProject: "flat-bottom-filter-drawdown",
    bedBehaviorUnderLoad: 'late-forming-crater',
    measurementNote: "Tested in size S with Orea Negotiator (compressed config). Size M not yet tested; size confound vs FLAT 2 FAST (tested in M) queued as audit item #9. Sibarist markets FLAT 2 as 'Zero-Bypass' design — micro-folds friction is a known tradeoff, not a defect. Exploratory Sibarist Booster 45 pull: 52s drawdown (-75.5s vs no-Booster) — Booster effectively converts B3 to free-seating-cluster speed.",
  },
  {
    name: "FLAT 2 FAST",
    manufacturer: "Sibarist",
    sku: "FLAT2-FAST",
    link: "https://sibarist.coffee/en-es/products/flat-2",
    paperShape: "Flat",
    sizeStandard: "Kalita-155/185",
    fitsBrewers: ["Orea", "Kalita", "April"],
    sealFitType: "Tight (zero-bypass per Sibarist design intent)",
    material: "Specialty fiber (FAST)",
    thickness: "Ultra-thin",
    crepeStructure: "Engineered (pre-folded v2)",
    flowRate: "Medium (Negotiator-compressed; measurement-revised from inherited 'Very fast' classification)",
    flowConsistency: "Extremely stable",
    bypassInteraction: "Neutral (Sibarist 'Zero-Bypass' design)",
    cloggingRisk: "Very low",
    clarity: "Very high",
    body: "Low",
    sweetnessExpression: "Clean",
    paperTechnology: "FAST (pre-folded v2)",
    bestArchetype: "Stability flat",
    compatibleSystems: "Orea / Kalita / April",
    owned: true,
    location: "Home",
    primaryUseCase: "Pre-folded clarity-forward flat extraction; FAST fiber in v2 pre-folded format",
    measuredDrawdownSec: 117,
    measurementDose: "15g",
    measurementBaseline: "Sibarist FLAT 2 B3 (Project #2 baseline; 127.5s median, 6s range)",
    measurementDate: "2026-05-24",
    measurementProject: "flat-bottom-filter-drawdown",
    bedBehaviorUnderLoad: 'late-forming-crater',
    measurementNote: "Tested in size M with Orea Negotiator (sits proud of brewer rim — see audit item #9 on size confound vs FLAT 2 B3 size S baseline); size S not yet tested. Cross-confirmed with FLAT FAST hand-fold (both at 117s exact). Exploratory Sibarist Booster 45 pull: 105s drawdown (-12s vs no-Booster) — much less Booster sensitivity than FLAT 2 B3 (which dropped -75.5s with Booster). Effect is fiber-specific OR size-specific (confounded).",
  },
  {
    name: "WAVE B3",
    manufacturer: "Sibarist",
    sku: "WAVE-B3",
    link: "https://sibarist.coffee/en-es/products/wave",
    paperShape: "Wave",
    sizeStandard: "Kalita-155/185",
    fitsBrewers: ["Orea", "Kalita", "Stagg"],
    sealFitType: "Tight (structured fit)",
    material: "Specialty fiber (B3)",
    thickness: "Medium",
    crepeStructure: "Engineered",
    flowRate: "Medium (Negotiator-compressed) / Fast (free-seating in Orea) — context-dependent",
    flowConsistency: "Extremely stable",
    bypassInteraction: "Reduces",
    cloggingRisk: "Very low",
    clarity: "High",
    body: "Medium",
    sweetnessExpression: "Structured",
    paperTechnology: "B3",
    bestArchetype: "Stability flat (controlled)",
    compatibleSystems: "Orea / Kalita",
    owned: true,
    location: "Home",
    primaryUseCase: "Controlled flat extraction; functionally a flat-bottom paper in Orea (cupcake walls free-seat without Negotiator)",
    measuredDrawdownSec: 48.5,
    measurementDose: "15g",
    measurementBaseline: "Sibarist FLAT 2 B3 (Project #2 baseline; 127.5s median)",
    measurementDate: "2026-05-24",
    measurementProject: "flat-bottom-filter-drawdown",
    bedBehaviorUnderLoad: 'late-forming-crater',
    measurementNote: "Free-seating in Orea v4 (no Negotiator); zero bypass observed. Same drawdown cluster as xBloom (48.5s vs xBloom's 50s) — geometry/compression dominates fiber. paperShape:'Wave' is misleading — functionally a flat-bottom paper with cupcake-walled geometry; see Project #2 audit item #2. flowRate is context-dependent: ~48s free-seating vs ~120-130s if Negotiator-compressed (not measured here but inferred from FLAT 2 B3 baseline behavior).",
  },
  {
    name: "UFO FAST",
    manufacturer: "Sibarist",
    sku: "UFO-FAST",
    link: "https://sibarist.coffee/en-es/products/ufo",
    paperShape: "Conical",
    sizeStandard: "Custom 80°",
    fitsBrewers: ["UFO dripper"],
    sealFitType: "Perfect fit (custom)",
    material: "Specialty fiber (FAST)",
    thickness: "Ultra-thin",
    crepeStructure: "Engineered",
    flowRate: "Very fast",
    flowConsistency: "Extremely stable",
    bypassInteraction: "Neutral",
    cloggingRisk: "Very low",
    clarity: "Very high",
    body: "Low",
    sweetnessExpression: "Clean",
    paperTechnology: "FAST",
    bestArchetype: "Clarity cone",
    compatibleSystems: "UFO",
    owned: true,
    location: "Home",
    primaryUseCase: "Extreme clarity expression (max bypass cone behavior)",
  },
  {
    name: "Sibarist HALO CONE FAST",
    manufacturer: "Sibarist",
    sku: "HALO-FAST",
    link: "https://sibarist.coffee/en-es/products/cone-bs",
    paperShape: "Conical (system-specific)",
    sizeStandard: "BS cone",
    fitsBrewers: ["Sibarist Brewing System (cone module)"],
    sealFitType: "Perfect seal (system-integrated)",
    material: "Specialty fiber (FAST)",
    thickness: "Ultra-thin",
    crepeStructure: "Engineered low resistance",
    flowRate: "Very fast",
    flowConsistency: "Extremely stable",
    bypassInteraction: "None (system sealed)",
    cloggingRisk: "Very low",
    clarity: "Very high",
    body: "Low",
    sweetnessExpression: "Clean",
    paperTechnology: "FAST",
    bestArchetype: "Clarity cone (system-level)",
    compatibleSystems: "Sibarist Brewing System",
    owned: true,
    location: "Home",
    primaryUseCase: "System-level peak clarity (eliminate fit + bypass variability)",
  },
  {
    name: "Sibarist HALO CONE B3",
    manufacturer: "Sibarist",
    sku: "HALO-B3",
    link: "https://sibarist.coffee/en-es/products/cone-bs",
    paperShape: "Conical (system-specific)",
    sizeStandard: "BS cone",
    fitsBrewers: ["Sibarist Brewing System (cone module)"],
    sealFitType: "Perfect seal (system-integrated)",
    material: "Specialty fiber (B3)",
    thickness: "Medium",
    crepeStructure: "Engineered high structure",
    flowRate: "Medium",
    flowConsistency: "Extremely stable",
    bypassInteraction: "None (system sealed)",
    cloggingRisk: "Very low",
    clarity: "High",
    body: "Medium",
    sweetnessExpression: "Structured",
    paperTechnology: "B3",
    bestArchetype: "Clarity cone (controlled system)",
    compatibleSystems: "Sibarist Brewing System",
    owned: true,
    location: "Home",
    primaryUseCase: "System-level structured clarity (max repeatability cone system)",
  },
  {
    name: "CONE 28 B3",
    manufacturer: "Sibarist",
    sku: "CONE28-B3",
    link: "https://sibarist.coffee/en-es/products/cone-28-30%C2%BA",
    paperShape: "Conical",
    sizeStandard: "Low-angle cone",
    fitsBrewers: ["Deep cone brewers"],
    sealFitType: "Tight",
    material: "Specialty fiber (B3)",
    thickness: "Medium",
    crepeStructure: "Engineered",
    flowRate: "Medium",
    flowConsistency: "Extremely stable",
    bypassInteraction: "Reduces",
    cloggingRisk: "Very low",
    clarity: "High",
    body: "Medium",
    sweetnessExpression: "Structured",
    paperTechnology: "B3",
    bestArchetype: "Clarity cone (controlled)",
    compatibleSystems: "Low-angle brewers, Funnex",
  },
  {
    name: "WAVE FAST",
    manufacturer: "Sibarist",
    sku: "WAVE-FAST",
    link: "https://sibarist.coffee/en-es/products/wave",
    paperShape: "Wave",
    sizeStandard: "Kalita-155/185",
    fitsBrewers: ["Orea", "Kalita", "Stagg"],
    sealFitType: "Tight (structured fit)",
    material: "Specialty fiber (FAST)",
    thickness: "Ultra-thin",
    crepeStructure: "Engineered",
    flowRate: "Very fast",
    flowConsistency: "Extremely stable",
    bypassInteraction: "Neutral",
    cloggingRisk: "Very low",
    clarity: "Very high",
    body: "Low",
    sweetnessExpression: "Clean",
    paperTechnology: "FAST",
    bestArchetype: "Stability flat",
    compatibleSystems: "Orea / Kalita",
  },
  {
    name: "FAST Trapezoid",
    manufacturer: "Sibarist",
    sku: "TRAP-FAST",
    link: "https://sibarist.coffee/en-es/products/fast-trapezoid",
    paperShape: "Trapezoid",
    sizeStandard: "102",
    fitsBrewers: ["Clever", "Melitta"],
    sealFitType: "Tight",
    material: "Specialty fiber (FAST)",
    thickness: "Ultra-thin",
    crepeStructure: "Engineered",
    flowRate: "Very fast",
    flowConsistency: "Extremely stable",
    bypassInteraction: "Neutral",
    cloggingRisk: "Very low",
    clarity: "Very high",
    body: "Low",
    sweetnessExpression: "Clean",
    paperTechnology: "FAST",
    bestArchetype: "Stability flat",
    compatibleSystems: "Clever / Melitta",
  },
  {
    name: "HYBRID FAST",
    manufacturer: "Sibarist",
    sku: "HYB-FAST",
    link: "https://sibarist.coffee/en-es/products/hybrid",
    paperShape: "Hybrid",
    sizeStandard: "Multi",
    fitsBrewers: ["Orea", "hybrid systems"],
    sealFitType: "Tight",
    material: "Specialty fiber (FAST)",
    thickness: "Ultra-thin",
    crepeStructure: "Engineered",
    flowRate: "Very fast",
    flowConsistency: "Extremely stable",
    bypassInteraction: "Neutral",
    cloggingRisk: "Very low",
    clarity: "Very high",
    body: "Low",
    sweetnessExpression: "Clean",
    paperTechnology: "FAST",
    bestArchetype: "Hybrid system",
    compatibleSystems: "Orea / hybrid brewers",
  },
  {
    name: "CONE BS FAST",
    manufacturer: "Sibarist",
    sku: "CONE-BS-FAST",
    link: "https://sibarist.coffee/en-es/products/cone-bs",
    paperShape: "Conical",
    sizeStandard: "V60-02",
    fitsBrewers: ["V60", "Origami"],
    sealFitType: "Tight",
    material: "Specialty fiber (FAST)",
    thickness: "Ultra-thin",
    crepeStructure: "Engineered",
    flowRate: "Very fast",
    flowConsistency: "Extremely stable",
    bypassInteraction: "Neutral",
    cloggingRisk: "Very low",
    clarity: "Very high",
    body: "Low",
    sweetnessExpression: "Clean",
    paperTechnology: "FAST",
    bestArchetype: "Clarity cone",
    compatibleSystems: "V60 / Origami",
  },
  {
    name: "CONE BS B3",
    manufacturer: "Sibarist",
    sku: "CONE-BS-B3",
    link: "https://sibarist.coffee/en-es/products/cone-bs",
    paperShape: "Conical",
    sizeStandard: "V60-02",
    fitsBrewers: ["V60", "Origami"],
    sealFitType: "Tight",
    material: "Specialty fiber (B3)",
    thickness: "Medium",
    crepeStructure: "Engineered",
    flowRate: "Medium",
    flowConsistency: "Extremely stable",
    bypassInteraction: "Reduces",
    cloggingRisk: "Very low",
    clarity: "High",
    body: "Medium",
    sweetnessExpression: "Structured",
    paperTechnology: "B3",
    bestArchetype: "Clarity cone (controlled)",
    compatibleSystems: "V60 / Origami",
  },
  {
    name: "Orea Z1 FAST",
    manufacturer: "Sibarist",
    sku: "Z1-FAST",
    link: "https://sibarist.coffee/en-es/products/orea-z1",
    paperShape: "Round",
    sizeStandard: "70mm",
    fitsBrewers: ["Orea Z1 (zero-bypass)"],
    sealFitType: "Perfect seal (zero bypass)",
    material: "Specialty fiber (FAST)",
    thickness: "Ultra-thin",
    crepeStructure: "Engineered",
    flowRate: "Very fast",
    flowConsistency: "Extremely stable",
    bypassInteraction: "None",
    cloggingRisk: "Very low",
    clarity: "Very high",
    body: "Low",
    sweetnessExpression: "Clean",
    paperTechnology: "FAST",
    bestArchetype: "Zero-bypass push",
    compatibleSystems: "Orea Z1",
  },
  {
    name: "Orea Z1 B3",
    manufacturer: "Sibarist",
    sku: "Z1-B3",
    link: "https://sibarist.coffee/en-es/products/orea-z1",
    paperShape: "Round",
    sizeStandard: "70mm",
    fitsBrewers: ["Orea Z1 (zero-bypass)"],
    sealFitType: "Perfect seal (zero bypass)",
    material: "Specialty fiber (B3)",
    thickness: "Medium",
    crepeStructure: "Engineered",
    flowRate: "Medium",
    flowConsistency: "Extremely stable",
    bypassInteraction: "None",
    cloggingRisk: "Very low",
    clarity: "High",
    body: "Medium",
    sweetnessExpression: "Structured",
    paperTechnology: "B3",
    bestArchetype: "Zero-bypass push (controlled)",
    compatibleSystems: "Orea Z1",
  },
  {
    name: "Orea FAST",
    manufacturer: "Sibarist",
    sku: "OREA-FAST",
    link: "https://sibarist.coffee/en-es/products/orea",
    paperShape: "Flat",
    sizeStandard: "Kalita-185",
    fitsBrewers: ["Orea V3", "V4"],
    sealFitType: "Tight (low bypass)",
    material: "Specialty fiber (FAST)",
    thickness: "Ultra-thin",
    crepeStructure: "Engineered",
    flowRate: "Very fast",
    flowConsistency: "Extremely stable",
    bypassInteraction: "Neutral",
    cloggingRisk: "Very low",
    clarity: "Very high",
    body: "Low",
    sweetnessExpression: "Clean",
    paperTechnology: "FAST",
    bestArchetype: "Stability flat",
    compatibleSystems: "Orea",
  },
  {
    name: "Orea B3",
    manufacturer: "Sibarist",
    sku: "OREA-B3",
    link: "https://sibarist.coffee/en-es/products/orea",
    paperShape: "Flat",
    sizeStandard: "Kalita-185",
    fitsBrewers: ["Orea V3", "V4"],
    sealFitType: "Tight (low bypass)",
    material: "Specialty fiber (B3)",
    thickness: "Medium",
    crepeStructure: "Engineered",
    flowRate: "Medium",
    flowConsistency: "Extremely stable",
    bypassInteraction: "Reduces",
    cloggingRisk: "Very low",
    clarity: "High",
    body: "Medium",
    sweetnessExpression: "Structured",
    paperTechnology: "B3",
    bestArchetype: "Stability flat (controlled)",
    compatibleSystems: "Orea",
  },
  {
    name: "Orea O1 FAST",
    manufacturer: "Sibarist",
    sku: "O1-FAST",
    link: "https://sibarist.coffee/en-es/products/orea-o1",
    paperShape: "Flat",
    sizeStandard: "Kalita-155",
    fitsBrewers: ["Orea V1", "small brewers"],
    sealFitType: "Tight (low bypass)",
    material: "Specialty fiber (FAST)",
    thickness: "Ultra-thin",
    crepeStructure: "Engineered",
    flowRate: "Very fast",
    flowConsistency: "Extremely stable",
    bypassInteraction: "Neutral",
    cloggingRisk: "Very low",
    clarity: "Very high",
    body: "Low",
    sweetnessExpression: "Clean",
    paperTechnology: "FAST",
    bestArchetype: "Stability flat",
    compatibleSystems: "Orea (small format)",
  },
  {
    name: "Orea O1 B3",
    manufacturer: "Sibarist",
    sku: "O1-B3",
    link: "https://sibarist.coffee/en-es/products/orea-o1",
    paperShape: "Flat",
    sizeStandard: "Kalita-155",
    fitsBrewers: ["Orea V1", "small brewers"],
    sealFitType: "Tight (low bypass)",
    material: "Specialty fiber (B3)",
    thickness: "Medium",
    crepeStructure: "Engineered",
    flowRate: "Medium",
    flowConsistency: "Extremely stable",
    bypassInteraction: "Reduces",
    cloggingRisk: "Very low",
    clarity: "High",
    body: "Medium",
    sweetnessExpression: "Structured",
    paperTechnology: "B3",
    bestArchetype: "Stability flat (controlled)",
    compatibleSystems: "Orea (small format)",
  },
  {
    name: "Origami FAST",
    manufacturer: "Sibarist",
    sku: "ORIGAMI-FAST",
    link: "https://sibarist.coffee/en-es/products/origami",
    paperShape: "Hybrid",
    sizeStandard: "V60-02 / Wave 155",
    fitsBrewers: ["Origami (cone + wave)"],
    sealFitType: "Adaptive (tightens seal)",
    material: "Specialty fiber (FAST)",
    thickness: "Ultra-thin",
    crepeStructure: "Engineered",
    flowRate: "Very fast",
    flowConsistency: "Extremely stable",
    bypassInteraction: "Neutral",
    cloggingRisk: "Very low",
    clarity: "Very high",
    body: "Low",
    sweetnessExpression: "Clean",
    paperTechnology: "FAST",
    bestArchetype: "Hybrid (clarity + flat)",
    compatibleSystems: "Origami",
  },
  {
    name: "Origami B3",
    manufacturer: "Sibarist",
    sku: "ORIGAMI-B3",
    link: "https://sibarist.coffee/en-es/products/origami",
    paperShape: "Hybrid",
    sizeStandard: "V60-02 / Wave 155",
    fitsBrewers: ["Origami (cone + wave)"],
    sealFitType: "Adaptive (tightens seal)",
    material: "Specialty fiber (B3)",
    thickness: "Medium",
    crepeStructure: "Engineered",
    flowRate: "Medium",
    flowConsistency: "Extremely stable",
    bypassInteraction: "Reduces",
    cloggingRisk: "Very low",
    clarity: "High",
    body: "Medium",
    sweetnessExpression: "Structured",
    paperTechnology: "B3",
    bestArchetype: "Hybrid (controlled)",
    compatibleSystems: "Origami",
  },
  {
    name: "April FAST",
    manufacturer: "Sibarist",
    sku: "APRIL-FAST",
    link: "https://sibarist.coffee/en-es/products/april",
    paperShape: "Flat",
    sizeStandard: "Kalita-155",
    fitsBrewers: ["April brewer"],
    sealFitType: "Tight (low bypass)",
    material: "Specialty fiber (FAST)",
    thickness: "Ultra-thin",
    crepeStructure: "Engineered",
    flowRate: "Very fast",
    flowConsistency: "Extremely stable",
    bypassInteraction: "Neutral",
    cloggingRisk: "Very low",
    clarity: "Very high",
    body: "Low",
    sweetnessExpression: "Clean",
    paperTechnology: "FAST",
    bestArchetype: "Stability flat",
    compatibleSystems: "April",
  },
  {
    name: "April B3",
    manufacturer: "Sibarist",
    sku: "APRIL-B3",
    link: "https://sibarist.coffee/en-es/products/april",
    paperShape: "Flat",
    sizeStandard: "Kalita-155",
    fitsBrewers: ["April brewer"],
    sealFitType: "Tight (low bypass)",
    material: "Specialty fiber (B3)",
    thickness: "Medium",
    crepeStructure: "Engineered",
    flowRate: "Medium",
    flowConsistency: "Extremely stable",
    bypassInteraction: "Reduces",
    cloggingRisk: "Very low",
    clarity: "High",
    body: "Medium",
    sweetnessExpression: "Structured",
    paperTechnology: "B3",
    bestArchetype: "Stability flat (controlled)",
    compatibleSystems: "April",
  },
  {
    name: "UFO B3",
    manufacturer: "Sibarist",
    sku: "UFO-B3",
    link: "https://sibarist.coffee/en-es/products/ufo",
    paperShape: "Conical",
    sizeStandard: "Custom 80°",
    fitsBrewers: ["UFO dripper"],
    sealFitType: "Perfect fit (custom)",
    material: "Specialty fiber (B3)",
    thickness: "Medium",
    crepeStructure: "Engineered",
    flowRate: "Medium",
    flowConsistency: "Extremely stable",
    bypassInteraction: "Reduces",
    cloggingRisk: "Very low",
    clarity: "High",
    body: "Medium",
    sweetnessExpression: "Structured",
    paperTechnology: "B3",
    bestArchetype: "Clarity cone (controlled)",
    compatibleSystems: "UFO",
  },
  {
    name: "Weber Bird FAST",
    manufacturer: "Sibarist",
    sku: "BIRD-FAST",
    link: "https://sibarist.coffee/en-es/products/weber-workshops-bird",
    paperShape: "Round",
    sizeStandard: "Custom",
    fitsBrewers: ["Weber Bird (vacuum)"],
    sealFitType: "Perfect seal (zero bypass)",
    material: "Specialty fiber (FAST)",
    thickness: "Ultra-thin",
    crepeStructure: "Engineered",
    flowRate: "Very fast",
    flowConsistency: "Extremely stable",
    bypassInteraction: "None",
    cloggingRisk: "Very low",
    clarity: "Very high",
    body: "Low",
    sweetnessExpression: "Clean",
    paperTechnology: "FAST",
    bestArchetype: "Zero-bypass push",
    compatibleSystems: "Weber Bird",
  },
  {
    name: "Weber Bird B3",
    manufacturer: "Sibarist",
    sku: "BIRD-B3",
    link: "https://sibarist.coffee/en-es/products/weber-workshops-bird",
    paperShape: "Round",
    sizeStandard: "Custom",
    fitsBrewers: ["Weber Bird (vacuum)"],
    sealFitType: "Perfect seal (zero bypass)",
    material: "Specialty fiber (B3)",
    thickness: "Medium",
    crepeStructure: "Engineered",
    flowRate: "Medium",
    flowConsistency: "Extremely stable",
    bypassInteraction: "None",
    cloggingRisk: "Very low",
    clarity: "High",
    body: "Medium",
    sweetnessExpression: "Structured",
    paperTechnology: "B3",
    bestArchetype: "Zero-bypass push (controlled)",
    compatibleSystems: "Weber Bird",
  },
  {
    name: "Weber Bird Paper Filters",
    manufacturer: "Weber Workshops",
    sku: "BIRD-FILTER",
    link: "https://weberworkshops.com/products/bird-paper-filters",
    paperShape: "Round (system-specific)",
    sizeStandard: "Bird standard",
    fitsBrewers: ["Weber Workshops Bird"],
    sealFitType: "Perfect seal (zero-bypass)",
    material: "Refined pulp",
    thickness: "Medium",
    crepeStructure: "Low",
    flowRate: "Medium-fast",
    flowConsistency: "Extremely stable",
    bypassInteraction: "None (zero bypass)",
    cloggingRisk: "Low",
    clarity: "High",
    body: "High",
    sweetnessExpression: "Structured-clean",
    paperTechnology: "Standard+",
    bestArchetype: "Zero-bypass push",
    compatibleSystems: "Weber Bird",
    owned: true,
    location: "Home",
    primaryUseCase: "Maximum extraction without bypass (pressure-driven saturation extraction)",
  },
  {
    name: "xBloom Premium Paper Filters",
    manufacturer: "xBloom",
    sku: "XBLOOM-STD",
    link: "https://xbloom.com/products/xbloom-premium-paper-filters",
    paperShape: "Flat",
    sizeStandard: "Kalita-155/185",
    fitsBrewers: ["xBloom", "Kalita", "Orea"],
    sealFitType: "Standard",
    material: "Refined pulp",
    thickness: "Thin",
    crepeStructure: "High",
    flowRate: "Fast",
    flowConsistency: "Very stable",
    bypassInteraction: "Neutral",
    cloggingRisk: "Low",
    clarity: "High",
    body: "Low",
    sweetnessExpression: "Clean",
    paperTechnology: "Standard+",
    bestArchetype: "Stability flat",
    compatibleSystems: "xBloom / Kalita / Orea",
    owned: true,
    location: "Home, Office",
    primaryUseCase: "Automated stability baseline (fast, consistent flat extraction)",
    measuredDrawdownSec: 50,
    measurementDose: "15g",
    measurementBaseline: "Sibarist FLAT 2 B3 (Project #2 baseline; 127.5s median)",
    measurementDate: "2026-05-24",
    measurementProject: "flat-bottom-filter-drawdown",
    bedBehaviorUnderLoad: 'late-forming-crater',
    measurementNote: "Free-seating in Orea v4 (no Negotiator); cupcake walls free-seat cleanly; zero bypass observed. Same drawdown cluster as WAVE B3 (50s vs WAVE B3's 48.5s) — geometry dominates fiber. WAVE B3 fits Orea slightly cleaner than xBloom Premium.",
  },
]

export const FILTER_NAMES: readonly string[] = FILTERS.map((f) => f.name)

export const FILTER_ALIASES: Record<string, string> = {
  "Espro Bloom": "xBloom Premium Paper Filters",
  "Espro Bloom (flat bottom)": "xBloom Premium Paper Filters",
  "Espro Bloom Flat": "xBloom Premium Paper Filters",
  "Espro Bloom - flat bottom": "xBloom Premium Paper Filters",
  "Espro Bloom flat-bottom filter": "xBloom Premium Paper Filters",
  "Espro Bloom (rinsed)": "xBloom Premium Paper Filters",
  "Sibarist UFO Fast Cone": "UFO FAST",
  "Filter: Sibarist UFO Fast Cone": "UFO FAST",
  "Sibarist B3 cone": "CONE B3",
  "Sibarist B3 flat, Size S": "FLAT B3",
  "Sibarist B3 Wave (size S)": "WAVE B3",
  "April brewer filter paper": "April Paper Filter",
  "April Brewer Paper": "April Paper Filter",
  "April Flat Bottom Paper": "April Paper Filter",
  "April paper filter": "April Paper Filter",
  "Hario V60 paper": "Hario V60 Paper Filter 01 (Tabbed)",
  "Hario V60 Paper": "Hario V60 Paper Filter 01 (Tabbed)",
  "Hario V60 white paper": "Hario V60 Paper Filter 01 (Tabbed)",
  "CAFEC Abaca Plus": "CAFEC Abaca+ Cup 1 Cone Paper Filter",
  "Standard flat filter (no puck screen)": "xBloom Premium Paper Filters",
  "Sibarist FAST Flat": "FLAT FAST",
  "Sibarist FAST flat": "FLAT FAST",
  "Sibarist FAST - flat bottom": "FLAT FAST",
  "Sibarist FAST - flat, size S": "FLAT FAST",
  "Sibarist FAST Flat - Size S": "FLAT FAST",
  "Sibarist FAST - Flat (Size S)": "FLAT FAST",
  "Sibarist FAST - Flat S": "FLAT FAST",
  // FLAT 2 aliases (Project #2, 2026-05-24): re-pointed from FLAT FAST to
  // FLAT 2 FAST after Step 0 surfaced these were silently collapsing distinct
  // products. Historical brew rows may need diagnostic audit — see Project #2
  // audit item #7.
  "Sibarist FAST Flat 2 - Size S": "FLAT 2 FAST",
  "Sibarist FAST - Flat 2, Size S": "FLAT 2 FAST",
  "Sibarist FAST Flat 2 - Size M": "FLAT 2 FAST",
  "Sibarist B3 Flat 2 - Size S": "FLAT 2 B3",
  "Sibarist B3 - Flat 2, Size S": "FLAT 2 B3",
  "Sibarist B3 Flat 2 - Size M": "FLAT 2 B3",
  "Sibarist Flat 2 FAST": "FLAT 2 FAST",
  "Sibarist Flat 2 B3": "FLAT 2 B3",
  "Sibarist FAST - Flat, Size M": "FLAT FAST",
  "Sibarist FAST (flat bottom, imperfect fit)": "FLAT FAST",
  "Sibarist FAST (flat bottom)": "FLAT FAST",
  "Sibarist FAST": "FLAT FAST",
  "Sibarist FAST Cone": "CONE FAST",
}

export const FILTER_LOOKUP: CanonicalLookup = makeCanonicalLookup(
  FILTER_NAMES,
  FILTER_ALIASES,
)

// Back-compat exports.
export const isCanonicalFilter = FILTER_LOOKUP.isCanonical
export const findClosestFilter = FILTER_LOOKUP.findClosest

export function getFilterEntry(name: string | null | undefined): FilterEntry | null {
  if (!name) return null
  const canonical = FILTER_LOOKUP.canonicalize(name)
  if (!canonical) return null
  return FILTERS.find((f) => f.name === canonical) ?? null
}

export function getFilterDisplayName(name: string | null | undefined): string {
  if (!name) return ''
  const e = getFilterEntry(name)
  return e?.displayName ?? e?.name ?? name
}
